### ISSUE TITLE
Active Job

### ISSUE THREAD

**Issue by rafaellima** [mhenrixon/sidekiq-unique-jobs#102]
I have been digging around with Active Job and I have had a hard time trying to find out how to use unique jobs with Active Job. The documentation on https://github.com/mhenrixon/sidekiq-unique-jobs#usage-with-activejob is not clear enough (not for me) and I haven't figured out how does this works.

There is no documentation outside this github page that explains this integration.

This in my config/initializers/sidekiq.rb
```ruby
Sidekiq.default_worker_options = {
   'unique' => true,
   'unique_args' => proc do |args|
     [args.first.except('job_id')]
   end
}
SidekiqUniqueJobs.config.unique_args_enabled = true
```

Can someone explain what `job_id` means?

After adding it I'm still able to enqueue the same worker with the same parameters:

```ruby
ExampleJob.perform_later(1)
Enqueued ExampleJob (Job ID: 5f18d0bb-4b2c-4a69-9056-688ec2ddd469) to Sidekiq(default) with arguments: 1
=> #<ExampleJob:0x007ff56dcef170 @arguments=[1], @job_id="5f18d0bb-4b2c-4a69-9056-688ec2ddd469", @queue_name="default">

ExampleJob.perform_later(1)
Enqueued ExampleJob (Job ID: 6155c416-9f6b-4620-aae4-080169fbda1a) to Sidekiq(default) with arguments: 1
=> #<ExampleJob:0x007ff56dcef170 @arguments=[1], @job_id="6155c416-9f6b-4620-aae4-080169fbda1a", @queue_name="default">
```

What am I doing wrong?

**Comment by guivinicius** [comment]
Same problem here. Anyone ?

**Comment by mhenrixon** [comment]
> Note that more advanced Sidekiq features (sidekiq_options) cannot be controlled or configured via ActiveJob, e.g. saving backtraces.

Meaning don't use active job if you need such functionality :)

**Comment by guivinicius** [comment]
@rafaellima

Actually, the code is working. The problem is that when you call `perform_later` on localhost it will run `now` unless you have another job hanging the queue.

Open the web panel and watch the schedules when you do:

```ruby
MyJob.set(wait: 1.minute).perform_later(1)
MyJob.set(wait: 1.minute).perform_later(1)
```

It will schedule only one job.

**Comment by Fredar** [comment]
It seems that this unique initializer wont work with jobs that include set:
`set(wait: 30.seconds)`

Not sure how it could be connected.

**Comment by guivinicius** [comment]
We actually dropped Activejob and start using plain Sidekiq jobs. It makes sense if you think that you're using too many specific Sidekiq things.

**Comment by Fredar** [comment]
Turns out that my problem was caused by something in version `3.0.14`.
https://github.com/mhenrixon/sidekiq-unique-jobs/issues/90#issuecomment-133448822

**Comment by rafaellima** [comment]
Turns out we had a migraine to get this integration (Active Job + Unique Jobs) working. We're moving to the good old Sidekiq + Unique Jobs integration.

@mhenrixon could you please close this issue?
