### ISSUE TITLE
3.0.15 apparently breaks inline testing

### ISSUE THREAD

**Issue by joelmichael** [mhenrixon/sidekiq-unique-jobs#113]
After a bundle update, I found that certain jobs weren't being queued in tests. I determined that it was because of the `unique: true`. Going back to 3.0.14 fixes the issue. This happens even if I add `require 'sidekiq_unique_jobs/testing'` to spec_helper.

**Comment by gilest** [comment]
We encountered a similar issue yesterday and managed to get around it by adding the following to spec_helper.

```ruby
require 'sidekiq_unique_jobs/testing/sidekiq_overrides'

config.before(:each) do
  Sidekiq::Worker.clear_all
end
```

It seems that otherwise the Redis state wasn't being entirely cleared between test runs.

**Comment by mhenrixon** [comment]
Report back if still broken when upgrading to 4.0.0
