### ISSUE TITLE
Don't work with perform_in

### ISSUE THREAD

**Issue by gauthier-delacroix** [mhenrixon/sidekiq-unique-jobs#114]
Hi,

I'd like to use Skidekiq `perform_in` feature with unique job so that I can trigger many `perform_in(10)` within 10 seconds and be sure it won't be run more than once per 10 seconds.

Unfortunately, it seems `sidekiq-unique-jobs` doesn't work well with `perform_in`: The first run works, but the lock is never released.

Running a `perform_async` will release the lock and I can run one `perform_in` and so on.

My worker is very simple, with no parameter in the `perform` method.

**Comment by gauthier-delacroix** [comment]
I've also noticed that `perform_in` only puts a lock for other `perform_in` calls. That means you can send a `perform_in` and a `perform_async` right after and both will be executed.

However, running a `perform_async` first will prevent `perform_in` executions until it's finished.

**Comment by mhenrixon** [comment]
See read for how to achieve this `unique_lock: :while_executing`
