### ISSUE TITLE
4.0.1 => job no longer unique

### ISSUE THREAD

**Issue by phuongnd08** [mhenrixon/sidekiq-unique-jobs#117]
After upgrade to 4.0.1 I start seeing jobs kept being queued without uniqueness awareness.

**Comment by mhenrixon** [comment]
You will have to specify the unique_lock for the job in that case. `unique_lock: :until_executed` for instance. The default lock type is now `while_executing`.

**Comment by mhenrixon** [comment]
@phuongnd08 check if the changes in 4277109da01551a0ed13bc949152eb88601aa052 helps you understand the problem better. If not I will try to improve it some more.

**Comment by phuongnd08** [comment]
I see hundred of job with the same type and arguments (no arguments actually) to be backlogged, so I don't think unique_lock value is the case.

**Comment by phuongnd08** [comment]
Oh, after reading the text I understand what you are saying. Let me verify my case.
