### ISSUE TITLE
Active job with unique args doesn't work

### ISSUE THREAD

**Issue by knarewski** [mhenrixon/sidekiq-unique-jobs#120]
Hello, the code snippet from readme does not seem to work:
```
Sidekiq.default_worker_options = {
   'unique' => true,
   'unique_args' => proc do |args|
     [args.first.except('job_id')]
   end
}
SidekiqUniqueJobs.config.unique_args_enabled = true
```
Short investigation showed, that during UniqueArgs initialization, on line:
`@item['unique_args'.freeze] ||= unique_args(@item['args'.freeze])`
The Proc is not executed, and gem just assumes that Proc object is an unique argument itself.

**Comment by mhenrixon** [comment]
Oh darn! I forgot about this, let me check what I can do..
