### ISSUE TITLE
Redis::CommandError: ERR unknown command 'eval'

### ISSUE THREAD

**Issue by jfelchner** [mhenrixon/sidekiq-unique-jobs#124]
Looks like this issue has cropped up again.

I'm on Redis 2.8.18 and using sidekiq-unique-jobs 3.0.15 with sidekiq version 3.5.0

https://github.com/mhenrixon/sidekiq-unique-jobs/issues/109

**Comment by mhenrixon** [comment]
Could it be that you confuse redis server version with redis gem version?

**Comment by jfelchner** [comment]
Nope.  Redis server is `2.8.18`.  Redis gem version is `3.2.1`.

**Comment by mhenrixon** [comment]
In that case I'd recommend you investigate how to upgrade to jobs 4.0.4. But the error he was posting is a dead give away that his redis didn't have lua support. If you get that error it means your redis version isn't accepting `eval('some luascript')` which means it is less than 2.6.

**Comment by jfelchner** [comment]
![image](https://cloud.githubusercontent.com/assets/285582/10385947/01dac2be-6e16-11e5-9f56-b17ee239db5b.png)

**Comment by mhenrixon** [comment]
I wasn't trying to imply you were lying to me I was just saying your problem isn't the same as the guy who reported #109 and there for probably not related. I suggested you look into upgrading :)

If you start your favourite rails/irb console, load sidekiq and try: 

```ruby
Sidekiq.redis { |c| c.eval('return redis.keys') }
```

What result do you get?
