### ISSUE TITLE
docs clarification

### ISSUE THREAD

**Issue by ivar** [mhenrixon/sidekiq-unique-jobs#130]
in the READE it says _"Version 4 requires redis 2.6.2!! Don't upgrade to version 4 unless you are on redis 2.6.2."_ - could you please clarify if you need exactly redis 2.6.2 or *at least* 2.6.2 ?

**Comment by mhenrixon** [comment]
Surprised that is even needed since there has been no breaking redis changes to my knowledge until today. Only newer versions API's can't be used in older versions but fine.... I'll be explicit about it.
