### ISSUE TITLE
sidekiq-unique-jobs not enabled from sidekiq workers

### ISSUE THREAD

**Issue by sanjayprabhu** [mhenrixon/sidekiq-unique-jobs#131]
I'm on sidekiq-unique-jobs [3.0.15](https://rubygems.org/gems/sidekiq-unique-jobs/versions/3.0.15) (which interestingly, doesn't seem to be tagged in github). And I just ran into an issue where jobs were not being de-duplicated when enqueued from sidekiq workers. Looks like this is because the client middleware is not enabled when configuring the server middleware. 

See 
https://github.com/mhenrixon/sidekiq-unique-jobs/commit/f4404ed6d26add06f51619525fe1f047932681cb#diff-3deeecb0f47a5e1af766a8ee39271b2eL8. 

I can open a PR with a fix if you like. I'm working around this by manually configuring it, but it'd be great to get a 3.0.16 with this fix.

**Comment by mhenrixon** [comment]
Still a problem? I wouldn't mind releasing a fixed version for this but the code pre-4.x is a mess and painful to work with so if you provide the fix I'll get it released. I'll close this for now while waiting for a pull request. Sounds fair?
