### ISSUE TITLE
Version 4 Upgrade

### ISSUE THREAD

**Issue by kapso** [mhenrixon/sidekiq-unique-jobs#133]
Little confused about the upgrade -- difference between Easy path & Hard path? We have many future (unique) jobs scheduled, do both upgrade paths require us to delete jobs?

If we just upgrade the code and dont delete the jobs, would things just work?

**Comment by mhenrixon** [comment]
If you state your needs I might be able to help you. Can you post the workers and the job hash from sidekiq so that I can see if there is an easy upgrade path I could develop for you?

**Comment by kapso** [comment]
Here's one example worker. 

```ruby
ChargeWorker.perform_in(Settings.charge_retry_days.days, @object.id, retry_random: rand.to_s)
```

```ruby
class ChargeWorker < BaseWorker
  sidekiq_options queue: :charge,
                  unique: :until_executed

  def perform(id, _options = {})
    ApplyCharge.call(id: id)
  end
end
```

We have other workers too, but this is one example. Thanks so much for your help.

**Comment by mhenrixon** [comment]
Ok so first things first! You job will always be unique because the arguments is using some type of random but maybe that is ok? I also don't see what your job configuration was previously which would be helpful to understand what is needed.

**Comment by kapso** [comment]
The only difference is `unique: true` old unique job syntax

**Comment by mhenrixon** [comment]
First of all the job will always be unique, not sure if you are aware of that?

**Comment by kapso** [comment]
Yea I understand that :) thats how it was intended due to `retry_random: rand.to_s`

**Comment by mhenrixon** [comment]
But you could as well not have it unique over that random thing. Every job with the id will be unique.

**Comment by kapso** [comment]
When the charge is processed for the first time i.e when job queued for the first time then we only use - `ChargeWorker.perform_in(Settings.charge_retry_days.days, @object.id)`  its for this use case that we are using unique jobs.

**Comment by mhenrixon** [comment]
What did the worker look like before? I am trying to understand what the job hash looks like in redis.

**Comment by kapso** [comment]
This is what it looks like right now - `gem 'sidekiq-unique-jobs', '3.0.15'`

```ruby
class ChargeWorker < BaseWorker
  sidekiq_options queue: :charge,
                  unique: true

  def perform(id, _options = {})
    ApplyCharge.call(id: id)
  end
end
```

**Comment by mhenrixon** [comment]
From what I can gather the example job should be upgraded automagically. Just make sure that the ApplyCharge class is protecting against actually applying charges by id more than once. I can only guarantee certain types of uniqueness most of them constrained to 1 hour maximum.

**Comment by kapso** [comment]
Got it. Thanks for your inputs and your work on this gem.
