### ISSUE TITLE
No mention how to test in README

### ISSUE THREAD

**Issue by denispeplin** [mhenrixon/sidekiq-unique-jobs#135]
I found some information in #24. `be_unique` is mentioned there. But it only works when `unique: true` and doesn't work, for example, for `unique: until_executed`.

Are there any other matchers? Or how to test uniqueness?

**Comment by mhenrixon** [comment]
No matchers unfortunately, I'll look into that but I also accept pull requests. Since uniqueness is usually something mission critical I'd go for the integration type of tests here if it is truly important.

**Comment by denispeplin** [comment]
Thank you, I'll look!

I also noticed, that I can specify anything in `unique` option, like `sidekiq_options unique: :anything`, and no error will occur, no warnings. What if I just will have a typo there? The job will be not unique, and I have no tests for that yet. But this is probably another issue.

**Comment by mhenrixon** [comment]
You will crash and burn and get notified about the issue. It will raise a `NameError` if I am not mistaken since the constant don't exist.

**Comment by denispeplin** [comment]
Actually, I tried that, and got nothing.

```ruby
class SomeJob
  include Sidekiq::Worker

  sidekiq_options unique: :anything, retry: false
```

```
gem 'sinatra'
gem 'sidekiq'
gem 'sidekiq-unique-jobs'
gem 'sidekiq-status'
gem 'sidekiq-statistic'

group :test do
  gem 'rspec-sidekiq'
end
```

All gems on their latest versions, Rails 4.2.4

**Comment by denispeplin** [comment]
And tried that again, and got `NameError: uninitialized constant SidekiqUniqueJobs::Lock::Anything`.

I forgot to mention, first time it was in test environments.

**Comment by denispeplin** [comment]
Tried to comment out `gem rspec-sidekiq`, then bundle, then run again. Still no errors.
Removed `require 'sidekiq_unique_jobs/testing'`

oops..

I found what it was. I probably did it wrong. I tested only `perform` action on object, but I should test `perform_async` instead.

Yes, now I'm getting error in test enviroment.

Thank you, sorry for wasting your time.

**Comment by mhenrixon** [comment]
No problem at all ;)
