### ISSUE TITLE
while_executing still runs duplicate tasks

### ISSUE THREAD

**Issue by Mehonoshin** [mhenrixon/sidekiq-unique-jobs#136]
Hi, folks!

Probably I'm doing something wrong, hope you'll help me.

I have following worker:

```
module ScheduledJobs
  class BaseWorker
    include Sidekiq::Worker

    sidekiq_options queue:  :scheduler,
                    unique: :while_executing,
                    log_duplicate_payload: true

    def perform
      fail 'Implement in child class'
    end
  end
end
```

It runs some periodic tasks, without any args.
And I don't want this tasks to be run simultaneously.

But if I start this job multiple times - all tasks will be running.

If I change :while_executing to :until_executed - then this task is run only once, and after its completion new tasks will not be processed.

Where is my mistake?

**Comment by mhenrixon** [comment]
None, the jobs are processing one at a time. The other two will wait until the first one is finished. It just looks like they are all running at the same time.

**Comment by Mehonoshin** [comment]
So it's normal, that I can see then under 'busy' tab in sidekiq dashboard?

**Comment by Mehonoshin** [comment]
Ok, lets move to the second issue.
Why a processed task is not starting again with :until_executed?

**Comment by mhenrixon** [comment]
I have absolutely no idea why your jobs aren't continuously processed after being executed. The lock gets cleared as the job is processed. Not heard about that problem before. Not sure what sidekiq queue is but if it is `scheduler` then that might be the problem.

**Comment by Mehonoshin** [comment]
BTW, I'm creating jobs via clockwork gem, without loading rails environment
