### ISSUE TITLE
Jobs not getting queued in v4

### ISSUE THREAD

**Issue by kapso** [mhenrixon/sidekiq-unique-jobs#138]
This DOES NOT work `4.0.7`

```ruby
# All these calls are fired within a minute
TestWorker.perform_in(1.minute, 23, "skskks") # This gets queued
TestWorker.perform_in(1.minute, 23, "skskks") # This does not get queued - Expected
TestWorker.perform_in(1.minute, 3633, "skskks") # This DOES NOT get queued??? Broken?
```

```ruby
class TestWorker < BaseWorker
  sidekiq_options queue: :test,
                  unique: :until_executed,
                  unique_args: :unique_args

  def self.unique_args(id, blob)
    [id]
  end

  def perform(id, blob)
    puts "TestWorker - #{id}"
  end
end
```

This works `3.0.15`

```ruby
# All these calls are fired within a minute
TestWorker.perform_in(1.minute, 23, "skskks") # This gets queued
TestWorker.perform_in(1.minute, 23, "skskks") # This does not get queued - Expected
TestWorker.perform_in(1.minute, 3633, "skskks") # This gets queued
```

```ruby
class TestWorker < BaseWorker
  sidekiq_options queue: :test,
                  unique: true,
                  unique_args: :unique_args

  def self.unique_args(id, blob)
    [id]
  end

  def perform(id, blob)
    puts "TestWorker - #{id}"
  end
end
```

**Comment by mhenrixon** [comment]
If you only care about uniqueness `while executing` why are you using another lock?

**Comment by mhenrixon** [comment]
Ah sorry misread, it is too early. might be your filter isn't working perhaps

**Comment by mhenrixon** [comment]
Try something like 

```ruby
def self.filtered_args(args)
    options = args.extract_options!
    [args.first, options['type']]
  end
```

Docs might need update

**Comment by kapso** [comment]
I am not sure what you mean. I only need unique filter on the first argument `id`. And 2nd parameter is not a `Hash`, its just a string blob. I tried the follow but still doesn't work

```ruby
def self.unique_args(args)
  [args.first]
end
```

**Comment by mhenrixon** [comment]
What type is args and what does it contain? Can you please paste that for me?

**Comment by kapso** [comment]
This is weird, but I have a `puts` statement in unique_args method and I dont the see it being printed. Is it possible that `unique_args` is not being invoked.

```ruby
def self.unique_args(args)
  puts "#{args.class} -- #{args}"
  [args.first]
end
```

**Comment by mhenrixon** [comment]
That is what I thought... I'll investigate that, do you have any global configuration set? If so could you paste it? Want to replicate your exact scenario.

**Comment by kapso** [comment]
Global configuration set? I am just pasting this from my rails app code.

**Comment by mhenrixon** [comment]
Do you get any warnings or such?

**Comment by kapso** [comment]
No warnings at all.

**Comment by mhenrixon** [comment]
Do the following: `Sidekiq.logger.level = Logger::DEBUG` then run the code again and paste the output,

**Comment by kapso** [comment]
I dont see any logs.

**Comment by mhenrixon** [comment]
Should be in the log directory under whatever filename sidekiq logs to (see https://github.com/mperham/sidekiq/wiki/Logging for information about sidekiq logging). You should be able to do something like `Sidekiq.logger = Logger.new(STDOUT)`
