### ISSUE TITLE
Crash handling

### ISSUE THREAD

**Issue by cpuguy83** [mhenrixon/sidekiq-unique-jobs#14]
Currently Unique Jobs does not handle crashes.  So if a sidekiq worker crashes whatever it was doing is lost (except for Sidekiq Pro).  When using a worker with unique those unique job keys persist in Redis with no way of clearing them out (short of deleting them manually).

**Comment by draffensperger** [comment]
I work on a Rails app that uses Sidekiq pro and we have run into issues with our jobs not being unique when a Sidekiq pro process crashes and it pulls from the reliable fetch queue. We have also had problems with jobs not being unique on retries. We ended up using some code similar to @kfalconer code above that checks for retried jobs but we also check for older actively running jobs. Here's a gist of the class we made: https://gist.github.com/draffensperger/a90e54426be60769f621 (we just call `return if duplicate_job?(args)` in our workers that include it). Job uniqueness under crashes and retries is helpful to us and I'm open to collaborating to get it into `siekiq-unique-jobs`. @mhenrixon, how complex do you think it would be to get uniqueness on crash restarts and retries and are you open to having it added in?

**Comment by mhenrixon** [comment]
I am definitely open to having a duplicate? check as part of uniqueness I think the code you gisted could be pretty much copied into unique jobs. Pull requests much appreciated :)

**Comment by draffensperger** [comment]
Sounds good. I'll try to do a PR for it in the next couple weeks.

**Comment by mhenrixon** [comment]
This should be fixed. If not open a new issue with a failing test.

**Comment by draffensperger** [comment]
@mhenrixon thanks for fixing it, and sorry that I didn't get to the PR... I was meaning to and got started at one point and then got caught up with other things.

**Comment by salmanasiddiqui** [comment]
I think I have reproduce this issue on
sidekiq (3.5.4)
sidekiq-unique-jobs (4.0.18)

my worker:
```
  sidekiq_options retry: false,
                  unique: :until_executed,
                  unique_args: -> (args) { [args.first] }
```
STR:

1. queue any long running job
2. run sidekiq process
3. kill it

Now we can't enqueue the same job for next 30 mins. Can we configure this 30 mins expiry time somehow?

Is this 30 mins expiry is the solution to the actual problem of not handling crashes at all?
