### ISSUE TITLE
Broken compatibility with Sidekiq 3.4

### ISSUE THREAD

**Issue by morganatwishpond** [mhenrixon/sidekiq-unique-jobs#140]
https://github.com/mhenrixon/sidekiq-unique-jobs/commit/cd1954248474c2c31f35c4fab4a2e8820b3b0a8b#diff-de9f106e9f00c47071520a6db18167cc breaks API compatibility with Sidekiq 3.4.1 when it comes to deleting jobs.

Specifically, https://github.com/mperham/sidekiq/blob/v3.4.1/lib/sidekiq/api.rb#L372 requires two params while https://github.com/mhenrixon/sidekiq-unique-jobs/commit/cd1954248474c2c31f35c4fab4a2e8820b3b0a8b#diff-de9f106e9f00c47071520a6db18167ccR71 accepts no params.

```
ArgumentError: wrong number of arguments (2 for 0)
	from gems/sidekiq-unique-jobs-4.0.7/lib/sidekiq_unique_jobs/sidekiq_unique_ext.rb:72:in `delete_ext'
	from gems/sidekiq-3.4.1/lib/sidekiq/api.rb:372:in `delete'
	from gems/sidekiq-unique-jobs-4.0.7/lib/sidekiq_unique_jobs/sidekiq_unique_ext.rb:23:in `delete_ext'
```

**Comment by mhenrixon** [comment]
Thanks for reporting, I'll have a look at it!

**Comment by warmwind** [comment]
I got exactly the same error

**Comment by cnluzhang** [comment]
Does this problem still appear in Sidekiq 4.x?

Thanks.

**Comment by zedtux** [comment]
+1 on this issue.

**Comment by zedtux** [comment]
Using `sidekiq` 4.0.2 and `sidekiq-cron` 4.2 all is working fine.

**Comment by theprogrammerin** [comment]
@mhenrixon I think #167 that should fix the problem. Can you please check.

**Comment by mhenrixon** [comment]
Looks like this should be fixed now!
