### ISSUE TITLE
Two Rails apps on the same server, but only one Sidekiq instances is working correctly

### ISSUE THREAD

**Issue by faramund** [mhenrixon/sidekiq-unique-jobs#141]
Hi,
I use sidekiq-unique-jobs with Action Mailer deliver_later method to make emails unique. My configuration is:

```ruby
Sidekiq.default_worker_options = {
  unique: :until_executed,
  unique_args: ->(args) { args.first.except('job_id') }
}
```

I use:
sidekiq 3.5.1
database redis (2.4.14)
redis-namespace (1.5.2)
sidekiq-unique-jobs (3.015)

Locally everything works correctly.

I have a production app and a bet app on the same server. 

redis configuration for production:
redis_address: redis://127.0.0.1:6379/0 
redis_namespace: paymentlink-prod

redis configuration for beta:
redis_address: redis://127.0.0.1:6379/1 
redis_namespace: paymentlink-beta

When everything works correctly on a production, then no jobs are queued on a beta. And vice versa. After deleting:
```ruby
Sidekiq.default_worker_options = {
  unique: :until_executed,
  unique_args: ->(args) { args.first.except('job_id') }
}
```
the production and the beta work correctly.

I have no idea what is wrong. Maybe it is bug or not.

**Comment by mhenrixon** [comment]
I strongly recommend you don't use ActiveJob as a first step and see if that fixes it. If not report back with details about the workers. Preferably some example application that replicates the problem.

I strongly recommend you have a look at setting `Sidekiq.logger.level = Logger::DEBUG` and see what the output says as well. Is it duplicated? Which arguments are used for uniqueness etc.
