### ISSUE TITLE
Ignore lock when jobs spawned from another sidekiq worker

### ISSUE THREAD

**Issue by antonzaytsev** [mhenrixon/sidekiq-unique-jobs#142]
Everything works correct, it is not spawn job twice (while it is in queue or processing), when I add job in queue from terminal manually. But somehow, when same job, with same params adds in queue it ignores lock and I have same job with same params processing by same sidekiq worker.

I have below sidekiq options for worker
    sidekiq_options unique: :until_executed

Is anyone have idea what the problem can be?

**Comment by antonzaytsev** [comment]
@mhenrixon please let me know if you have any thoughts. This issue is critical for production app. Thank you!

**Comment by mhenrixon** [comment]
Preferably to help you speed up a fix provide a failing example application or test.

**Comment by antonzaytsev** [comment]
@mhenrixon thanks for response.
Here is simple app https://github.com/antonzaytsev/sidekiq-unique-jobs-app
Steps to reproduce:
1. Install rails with database and bundle;
2. Open web view localhost:3000/sidekiq
3. Start sidekiq worker with 
    bundle exec sidekiq -C config/sidekiq.yml
4. Open terminal and spawn job twice to check if lock works
    SimpleWorker.perform_async '1'
5. Right after add in queue another worker, which will spawn SimpleWorker
    SpawnSimpleWorker.perform_async '1'
6. Check webview it will contain 2 processing SimpleWorker with same arg

**Comment by goodgravy** [comment]
@mhenrixon version 3.0.15 of the gem appears to have been shipped with this problem, and is still available [on RubyGems](https://rubygems.org/gems/sidekiq-unique-jobs/versions/3.0.15). Could you yank it so that people can't use that version by accident?

Thanks!

**Comment by mhenrixon** [comment]
Done @goodgravy
