### ISSUE TITLE
Error when using unique_args in 4.0.8

### ISSUE THREAD

**Issue by kapso** [mhenrixon/sidekiq-unique-jobs#145]
Getting this error - `ArgumentError: wrong number of arguments (1 for 2)`  when running this code https://github.com/mhenrixon/sidekiq-unique-jobs/issues/138

And the error is reported at this line `def self.unique_args(id, blob)`

**Comment by mhenrixon** [comment]
Try changing to:

```ruby 
def self.unique_args(args)
 [args.first]
end
```

**Comment by mark-ellul** [comment]
Could the documentation in the Readme be updated to reflect the resolution to this issue?
