### ISSUE TITLE
Until Executed vs Unique Until And While Executing is confusing in README

### ISSUE THREAD

**Issue by rafaelsales** [mhenrixon/sidekiq-unique-jobs#148]
Still having hard time to see difference between Until Executed vs Unique Until And While Executing.

Text has some typos that might be making harder to understand as well.

For the one who implemented, it might be easy to understand though. If one could explain better here I could even try to revisit the README to make it easier to understand.

Thanks

**Comment by mhenrixon** [comment]
Feel free to provide a pull request with the typos fixed.

**Comment by mhenrixon** [comment]
Means the job is unique in two ways but only one at the time.

**Comment by RKushnir** [comment]
@mhenrixon It's not a typo, it's an unfinished sentence. Nobody(except maybe the author if he still remembers what he wanted to say) knows how to fix that. And in 2+ years it still hasn't been fixed. So your aggressive tone is not justified.

<img width="905" alt="screen shot 2018-01-18 at 10 47 27 am" src="https://user-images.githubusercontent.com/205906/35091776-d17f1ee0-fc3d-11e7-8cd7-17603fc712de.png">
