### ISSUE TITLE
Until Executed is taking waiting for unique_expiration

### ISSUE THREAD

**Issue by rafaelsales** [mhenrixon/sidekiq-unique-jobs#149]
1. I enqueue job A that uses until_executed
2. Start sidekiq and process that job
3. Stop sidekiq
4. Try to enqueue job A, and it doesn't enqueue

**Comment by mhenrixon** [comment]
Happy to try and help you get to the bottom of the problem but I have a whole bunch of tests saying that shouldn't be happening so unless you can provide a way to replicate the problem I am not going to investigate it.

I'll close this for now but I will reopen it when you give me a way to replicate your problem.
