### ISSUE TITLE
Release a new version for Ruby < 2.1 compatability

### ISSUE THREAD

**Issue by joeyschoblaska** [mhenrixon/sidekiq-unique-jobs#152]
Trying to load this gem in Ruby 2.0, I get the following error: 

```
shared/bundle/ruby/2.0.0/gems/sidekiq-unique-jobs-4.0.9/lib/sidekiq_unique_jobs/util.rb:12: syntax error, unexpected ','
    def del_by(pattern = SCAN_PATTERN, count:, dry_run: true)
```

The required keyword syntax being used for the "count" parameter wasn't introduced until Ruby 2.1. I saw that this was fixed in master with this commit (https://github.com/mhenrixon/sidekiq-unique-jobs/commit/045ca8935bb3e68d064c3c57987bcaa1c20dfe27), but there hasn't been a new version of the gem since that change. Doing a version bump should fix this problem for me and others.

Thanks for the great gem!

**Comment by mhenrixon** [comment]
Ah sorry about that! I'll do it first thing tomorrow!

>

**Comment by brandonjoyce** [comment]
Ran into this today as well.  Can I just use a different version of the gem temporarily?

**Comment by mhenrixon** [comment]
Sorry about the delay, had some unfinished changes locally. Could you check and see if the recent release fixes your issue?

**Comment by joeyschoblaska** [comment]
Hmm, now I'm getting a new error: `uninitialized constant SidekiqUniqueJobs::Scripts::SingleForwardable`

```
$ rvm use 2.0
$ gem install sidekiq-unique-jobs -v 4.0.9
$ gem list | grep sidekiq
sidekiq (4.0.1)
sidekiq-unique-jobs (4.0.9)

$ ruby -e "require 'rubygems'; require 'sidekiq-unique-jobs'"
/Users/joey/.rvm/rubies/ruby-2.0.0-p645/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require': /Users/joey/.rvm/gems/ruby-2.0.0-p645/gems/sidekiq-unique-jobs-4.0.9/lib/sidekiq_unique_jobs/util.rb:12: syntax error, unexpected ',' (SyntaxError)
    def del_by(pattern = SCAN_PATTERN, count:, dry_run: true)

$ gem uninstall sidekiq-unique-jobs
$ gem install sidekiq-unique-jobs
$ gem list | grep sidekiq
sidekiq (4.0.1)
sidekiq-unique-jobs (4.0.10)

$ ruby -e "require 'rubygems'; require 'sidekiq-unique-jobs'"
/Users/joey/.rvm/gems/ruby-2.0.0-p645/gems/sidekiq-unique-jobs-4.0.10/lib/sidekiq_unique_jobs/scripts.rb:14:in `<module:Scripts>': uninitialized constant SidekiqUniqueJobs::Scripts::SingleForwardable (NameError)
  from /Users/joey/.rvm/gems/ruby-2.0.0-p645/gems/sidekiq-unique-jobs-4.0.10/lib/sidekiq_unique_jobs/scripts.rb:7:in `<module:SidekiqUniqueJobs>'
```

**Comment by mhenrixon** [comment]
You want version 4.0.10 I think. SingleForwardable has been available
since forever.
>
>

**Comment by mhenrixon** [comment]
Not sure if you are aware but ruby 2.0 won't be maintained after end of February. Time to upgrade.

**Comment by joeyschoblaska** [comment]
Ah, "forwardable" needs to be explicitly required somewhere.

```
$ rvm use 2.2
$ gem list | grep sidekiq
sidekiq (4.0.1)
sidekiq-unique-jobs (4.0.10)

$ ruby -e "require 'rubygems'; require 'sidekiq-unique-jobs'"
/Users/joey/.rvm/gems/ruby-2.2.2/gems/sidekiq-unique-jobs-4.0.10/lib/sidekiq_unique_jobs/scripts.rb:14:in
  `<module:Scripts>': uninitialized constant SidekiqUniqueJobs::Scripts::SingleForwardable (NameError)

$ ruby -e "require 'rubygems'; require 'forwardable'; require 'sidekiq-unique-jobs'"
(no error)
```

**Comment by mhenrixon** [comment]
Fixed in https://github.com/mhenrixon/sidekiq-unique-jobs/commit/d4c24b1ea697b561e74ff507122442f0bc0f655e v4.0.11

**Comment by joeyschoblaska** [comment]
Awesome. Thanks a lot!
