### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by heaven** [mhenrixon/sidekiq-unique-jobs#155]
Seeing this in the sidekiq's log:
```
2015-12-17T17:42:03.264Z 31734 TID-1nasn0 ERROR: Too many open files @ rb_sysopen - /var/www/crm.wegohealth.com/shared/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.9/redis/aquire_lock.lua
2015-12-17T17:42:03.265Z 31734 TID-1nasn0 ERROR: /var/www/crm.wegohealth.com/shared/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.9/lib/sidekiq_unique_jobs/scripts.rb:39:in `read'
```

Also found the gem is not reliable some times, there are orphaned locks in the queue, and they supposed to contain the job id, but sometimes they contain one of these values: `[]`, `null`, `false`.

UPD: all this was observed with `4.0.9`, just upgraded to `4.0.13`, testing.

**Comment by mhenrixon** [comment]
You need to upgrade to 4.0.13 I think the latest version is. Regarding too
many open files that should have nothing to do with this gem. There are
plenty of information on that specific subject on the interwebz.

**Comment by heaven** [comment]
Yeah, I increased the ulimit already, but this error was always happening namely on aquire_lock.lua line, seemed weird to me, that's why I posted here.

**Comment by heaven** [comment]
Btw it seems it does work well with 4.0.13, thx.

**Comment by mhenrixon** [comment]
I'll have a look at it but the way it works is that the gem reads the contents of the file. The scripts are then cached in redis. The only time this would be a problem is if either the files was always read or the thing i would like to investigate the file is not closed.
