### ISSUE TITLE
Uniqueness breaks jobs

### ISSUE THREAD

**Issue by kholbekj** [mhenrixon/sidekiq-unique-jobs#160]
After upgrading to sidekiq 4 it appears that adding the unique option breaks job scheduling completely for me.

```ruby
class RecalculatePostRecommendationsJob
  include Sidekiq::Worker

  sidekiq_options queue: :lowest, unique: :until_executing

  def perform(post_id)
    post = Post.find(post_id)
    Recommendation.recalculate_all_for!(post)
  end
end
```

My spec:
```ruby
  it 'is triggered when a post is created', sidekiq: :inline do
    expect_any_instance_of(RecalculatePostRecommendationsJob).to receive(:perform).with(47)
    create :post, id: 47
  end
```

The spec will pass if i remove the unique option.
Also, in a console I'm not able to add the jobs to an empty queue
```ruby
(1)> RecalculatePostRecommendationsJob.perform_in(5.minutes, 1)
=> 5374aff8026836612515e291
(2)> Sidekiq::Queue.new('lowest').size
=> 0
```

If i remove the unique option everything works as it used to. 

Sidekiq 4.1.0, sidekiq-unique-jobs 4.0.13

**Comment by mhenrixon** [comment]
Thanks for reporting! I'll try and replicate it locally.

**Comment by kholbekj** [comment]
Aaaaand we were missing `require 'sidekiq_unique_jobs/testing'` in spec helper.
So if you can just shoot me, that'd be great.

**Comment by mhenrixon** [comment]
Thank you for for posting the solution @kholbekj.
