### ISSUE TITLE
No place where I can say "Thank you" for all contributors

### ISSUE THREAD

**Issue by LongMan** [mhenrixon/sidekiq-unique-jobs#165]
Thank you guys! Very useful gem.

Another place to say it not found ;-)

**Comment by mhenrixon** [comment]
You are right! That is so lame :) How about https://gitter.im/mhenrixon/sidekiq-unique-jobs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge ?

**Comment by LongMan** [comment]
Nice if you'll add it to README. Hard to be aware of all github-related services )

**Comment by mhenrixon** [comment]
check :)
