### ISSUE TITLE
unique: :while_executing doesn't remove lock when the Sidekiq node running the job shuts down and terminates the job prematurely

### ISSUE THREAD

**Issue by gabosgab** [mhenrixon/sidekiq-unique-jobs#170]
**Steps to Repro Issue**
1. Start sidekiq server and schedule a job that has no parameters and unique: :while_executing
2. Run the job, ensuring that it takes longer than 60 seconds to run
3. Restart the sidekiq server before the job has time to finish 
`* Notice in the logfile "WARN: Work still in progress struct Sidekiq::BasicFetch::UnitOfWork queue="queue:default", job="{\"class\":\"RankAllPlayersWorker\",\"args\":[],\"retry\":true,\"queue\":\"default\",\"unique\":\"while_executing\",\"jid\":\"389bafa99658b2679494dd0a\",\"created_at\":1456965258.3860772,\"unique_prefix\":\"uniquejobs\",\"unique_args\":[],\"unique_digest\":\"uniquejobs:8a7e705baa3fdded5698e7420f3d0fd5\",\"enqueued_at\":1456965258.39234}"
`
4. Try to schedule the job, notice that no job ID is returned and can never be scheduled until the lock is manually deleted

**Workaround**
1. Using your favorite Redis tool, goto the server and manually delete the lock.
2. Re-run the job, tada!

**Expected Behavior**
The node that is running the job should release the lock before shutting down and terminating the job to ensure that future nodes can run.  This is specific to jobs with no arguments.

**Comment by mhenrixon** [comment]
Not sure how much I can do about this. Like @mperham already suggested at some point you might have to increase your sidekiq `:timeout: 30` to however long your job takes to finish. 

To my knowledge there are no cleanup hooks that I can use to remove the uniqueness lock when sidekiq shuts down so you are probably on your own in this scenario. . If you have a look [here](https://github.com/mhenrixon/sidekiq-unique-jobs/blame/master/lib/sidekiq_unique_jobs/lock/until_executed.rb#L23) you can see that I am doing everything I can to clean up.  If sidekiq isn't operable how am I supposed to unlock the job?

I added some logging for when sidekiq is shutting down. At least that should ease debugging a little.

**Comment by mhenrixon** [comment]
Check https://github.com/mperham/sidekiq/wiki/Signals for information about how to use sidekiq signals and how timeout works.

**Comment by gabosgab** [comment]
I'm wondering if it's possible for the scheduler to know its previous host name and process id that was responsible for the lock and once it exits, to release all locks it owns.  Optionally have it cleanup locks if any exist on start as well.  Currently this is a long running job which timeouts will not work. That's assuming it's coming up on the same node. 

Optionally another method could be for the scheduler to have a timeout stored on the lock and it refreshes the lock as a method of keep alive. Otherwise any other node can destroy the lock.  That way state is not tied to a single node and other nodes can cleanup if necessary. Would that work?

**Comment by mhenrixon** [comment]
I'm open for suggestions (and pull requests) on this matter. You can set some timeouts and such in the worker configuration.

**Comment by jtomaszewski** [comment]
@gabosgab How did you resolve that in the end? by increasing timeouts?

**Comment by gabosgab** [comment]
@jtomaszewski I didn't end up working on the project long enough to solve it. :(  Timeouts wouldn't fix this since it stores the lock in Redis directly.  Only deleting the keys it uses to lock from Redis manually fixes the issue.
