### ISSUE TITLE
strange behaviour

### ISSUE THREAD

**Issue by rainerborene** [mhenrixon/sidekiq-unique-jobs#172]
```ruby
class DomainWorker
  include Sidekiq::Worker

  sidekiq_options queue: :platform, backtrace: true, unique: :until_executing

  def perform(account_id)
    account = Account.find account_id
    account.domains.each(&:sync!)
  end
end

# run in console
1000.times { DomainWorker.perform_async(4) }
```

You will notice that more than 1 job will be processed by Sidekiq. Any ideas how to solve this issue?

**Comment by mhenrixon** [comment]
I have some ideas but been traveling a lot over the last couple of months. Will get this fixed in the next release.

**Comment by heaven** [comment]
The `until_executing` option makes a job unique before Sidekiq started to perform it, right? So is it possible your job finishes faster than `1000.times { DomainWorker.perform_async(4) }`, the lock gets removed and Sidekiq is then allowed to queue one more job?

**Comment by mhenrixon** [comment]
Check https://github.com/mhenrixon/sidekiq-unique-jobs/releases/tag/v4.0.18
