### ISSUE TITLE
How do I use variables from another middleware in the unique_args?

### ISSUE THREAD

**Issue by NielsKSchjoedt** [mhenrixon/sidekiq-unique-jobs#173]
Hi I have another middleware that looks like this:

```ruby
    module Middleware

      class Client
        def call(_worker_class, item, _queue, _redis_pool=nil)
          item["au_country"] ||= CountryManager.country.to_s
          yield
        end
      end

      class Server
        def call(_worker_class, item, queue)
          CountryManager.country = item['au_country'].to_sym
          yield
        end
      end

    end
```

As you have probably guessed, I would like to use that item['au_country'] in the unique_args...?

**Comment by mhenrixon** [comment]
You should be able to just use the filter proc and tell it to make that argument part of the unique arguments. Not sure what you have so I can't really guide you more than this unless you provide where you are at.
