### ISSUE TITLE
Can't enable testing with newer versions of sidekiq

### ISSUE THREAD

**Issue by Slania** [mhenrixon/sidekiq-unique-jobs#175]
https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib/sidekiq_unique_jobs/testing/sidekiq_overrides.rb#L15

Couldn't understand the motivation behind that check, but with https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/testing.rb#L52, that will never proc.

**Comment by mhenrixon** [comment]
Sorry its taken so long. Seems to present itself frequently in the current master in similar but not identical ways. I'll get this fixed for the next release.

**Comment by mhenrixon** [comment]
https://github.com/mhenrixon/sidekiq-unique-jobs/releases/tag/v4.0.18
