### ISSUE TITLE
Duplicate jobs when using :until_and_while_executing

### ISSUE THREAD

**Issue by xanview** [mhenrixon/sidekiq-unique-jobs#181]
I have jobs configured to use :until_and_while_executing, when I look at the workers, I am seeing some duplicate tasks :( - any ideas?

I am using rails (5.0.0.beta4), sidekiq-unique-jobs (4.0.17) and sidekiq (4.1.1)

```ruby
>> Sidekiq::Workers.new.each {|process_id, thread_id, work| pp work}
{"queue"=>"status",
 "payload"=>
  {"class"=>"NetworkScanWorker",
   "args"=>[],
   "retry"=>false,
   "queue"=>"status",
   "backtrace"=>true,
   "unique"=>"until_and_while_executing",
   "jid"=>"d4e9de4f069a15f4d0544c70",
   "created_at"=>1462288501.2952945,
   "unique_prefix"=>"uniquejobs",
   "unique_args"=>[],
   "unique_digest"=>"uniquejobs:a27de2dcbeb3d9edc7f729ea2b460bbf",
   "enqueued_at"=>1462288501.3036587},
 "run_at"=>1462288534}
{"queue"=>"status",
 "payload"=>
  {"class"=>"NetworkScanWorker",
   "args"=>[],
   "retry"=>false,
   "queue"=>"status",
   "backtrace"=>true,
   "unique"=>"until_and_while_executing",
   "jid"=>"ab1681e2d8913365b27b596c",
   "created_at"=>1462288523.720068,
   "unique_prefix"=>"uniquejobs",
   "unique_args"=>[],
   "unique_digest"=>"uniquejobs:a27de2dcbeb3d9edc7f729ea2b460bbf",
   "enqueued_at"=>1462288523.7219687},
 "run_at"=>1462288534}

**Comment by xanview** [comment]
I switched to https://github.com/krasnoukhov/sidekiq-middleware and so far no issues.

The test case I'm using is this:

test_worker.rb
```
class TestWorker
  include Sidekiq::Worker
  sidekiq_options queue: :status, retry: false, backtrace: true, unique: :all

  def perform(argument)
    `sleep 120`
  end
end

```

start sidekiq and rails c. Run this in console:

```ruby
loop { TestWorker.perform_async('asd'); sleep 0.1 }
```

Monitor how many sleep processes are running:
```
while true; do ps aux | grep -i sleep | grep -v grep; sleep 5; echo; done
```

With sidekiq-unique-jobs, I am seeing 2 duplicate sleep jobs, with sidekiq-middleware I do not, hmm.

**Comment by mhenrixon** [comment]
Check https://github.com/mhenrixon/sidekiq-unique-jobs/releases/tag/v4.0.18

**Comment by pjar** [comment]
I'm still experiencing it with the following stack:

rails (3.2.22.1), redis-rails (3.2.4), sidekiq (4.1.1) ,sidekiq-failures (0.4.5), sidekiq-status (0.5.4), sidekiq-unique-jobs (4.0.18)

I always see 2 jobs created every time when there was no similar job ongoing, and after that uniqueness seems to work. How I understood this - this should let have only 1 job queued while at most 1 job is running. Looks like instead of queueing it runs the second job.

**Comment by mhenrixon** [comment]
Can you try `lock: :until_executed` and report back what happens?

**Comment by pjar** [comment]
@mhenrixon  it works fine with `unique: :until_executed` - it keeps running only 1 job and keeps sidekiq from queueing a similar one - but I need to allow queueing a job while similar one is running. Can I help you somehow with this?

**Comment by pjar** [comment]
@mhenrixon I've changed now to `unique: :while_executing` and it also seems not to work properly. It runs similar jobs immediately (I have 3 of them running now), while I understood that it allows running only 1 job of a kind while allowing to queue unlimited amount of similar ones.

**Comment by mhenrixon** [comment]
Thanks for narrowing it down @pjar. I'll look into it

**Comment by dprater** [comment]
I'm seeing the same issue with rails 4.2.6, sidekiq 4.1.2, and sidekiq-unique-jobs 4.0.18. However, I'm seeing it for both `unique: :until_executed` and `unique: :until_and_while_executed`. It consistently allows 2 jobs to be executing simulataneously, then will block queueing/execution for a while. However, it will then (seemingly randomly) allow jobs to be queued/executed sometimes. For example, if 2 duplicate jobs are executing, I can try 10 times to enqueue another job and it will correctly block that from occurring, However, on the 11th try (or some seemingly random number), it might let one more job get queued, then will go back to blocking.

**Comment by tnorthb** [comment]
Was running into this today, solved it by using `lock_expiration`.

The default `lock_expiration` is 1 minute, so if you have jobs that are unique `until_and_while_executing` and regularly take longer than 1 minute to run, you'll want to leverage the `lock_expiration` setting to extend the lock further to offer more protection
