### ISSUE TITLE
Parameters turn into String

### ISSUE THREAD

**Issue by felipeclopes** [mhenrixon/sidekiq-unique-jobs#182]
The issue happens when sidekiq-unique-jobs is added to Gemfile, 

Once I added the ```sidekiq-uniq-jobs``` all the parameters started being evaluated as string, even simple DateTime ones. I just removed the gem and the system was back to normal.

Is this an expected behavior or is it a bug?

*Gemfile.lock*
``` ruby
    sidekiq (4.1.2)
      concurrent-ruby (~> 1.0)
      connection_pool (~> 2.2, >= 2.2.0)
      redis (~> 3.2, >= 3.2.1)
    sidekiq-unique-jobs (4.0.17)
      sidekiq (>= 2.6)
      thor
```

I wonder if this happens only in the newer versions

**Comment by mhenrixon** [comment]
https://github.com/mperham/sidekiq/wiki/Best-Practices#make-your-job-parameters-small-and-simple
