### ISSUE TITLE
unique while not sucessfully completed?

### ISSUE THREAD

**Issue by mikebaldry** [mhenrixon/sidekiq-unique-jobs#185]
If the job is executed and fails, and is therefore sitting in the retry queue, others can still get added.. Is there any way around this?

**Comment by mhenrixon** [comment]
Might be possible to solve, haven’t looked in to that before.

**Comment by mikebaldry** [comment]
Thanks for the quick response. I'm using a unique timeout at the moment. Its not ideal, but for my situation its fine.

**Comment by mhenrixon** [comment]
I'd recommend keeping this state in something like your database instead.
