### ISSUE TITLE
not able to run test without live Redis

### ISSUE THREAD

**Issue by sevaorlov** [mhenrixon/sidekiq-unique-jobs#186]
Hi, we added `allow(Redis).to receive(:new).and_return MockRedis.new` to our tests, so that live Redis is not required in tests.

When I updated `sidekiq-unique-jobs` gem I got an error here https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib/sidekiq-unique-jobs.rb#L61 because of `c.info('server'.freeze)` returns `nil` if `c` is `MockRedis`. I was able to stub it, but then I got another error here https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib/sidekiq_unique_jobs/scripts.rb#L27, because these functions are not properly supported in `MockRedis`, maybe that is just a limitation for 'in-memory' redis.

So it appears that I'm not able to run my tests without live Redis if I use `sidekiq-unique-jobs` gem in my codebase. Can you suggest anything? 

Thanks

**Comment by sevaorlov** [comment]
I can stub `SidekiqUniqueJobs::Scripts`, but not sure if it won't break anything. And also there are problems with stubbing it, maybe because of `module_function`.

**Comment by coliver** [comment]
I am also experiencing this issue.

**Comment by mhenrixon** [comment]
https://github.com/mhenrixon/sidekiq-unique-jobs/releases/tag/v4.0.18
