### ISSUE TITLE
Could not find a valid gem 'sidekiq-unique-jobs' (= 3.0.15) in any repository

### ISSUE THREAD

**Issue by paveldruzyak** [mhenrixon/sidekiq-unique-jobs#197]
```
> gem install sidekiq-unique-jobs -v 3.0.15
ERROR:  Could not find a valid gem 'sidekiq-unique-jobs' (= 3.0.15) in any repository
```
Someone has an idea why this could happen?

**Comment by mhickman** [comment]
@mhenrixon - This broke our build as well, any reason the gem was yanked from rubygems?

**Comment by mhenrixon** [comment]
Gem is reported broken

**Comment by aCandidMind** [comment]
Can you please extend the [info on upgrading to 4.x](https://github.com/mhenrixon/sidekiq-unique-jobs#version-4-upgrade-instructions) or acknowledge my guess below. The changelog mentions `100% breaking changes` for version 4.0.0. I guess the change is that you no longer simply put `sidekiq_options :unique => true` but have to decide on the way you want your uniqueness to be enforced as per the [Locking](https://github.com/mhenrixon/sidekiq-unique-jobs#locking) section.
