### ISSUE TITLE
disappearing jobs - known issue in conjunction with other extensions?

### ISSUE THREAD

**Issue by dbenjamin57** [mhenrixon/sidekiq-unique-jobs#202]
Hi there, we have encountered an issue that some jobs dont get executed even though they get enqueued(we see them in the enqueued tab in sidekiq web ui). We can't really replicate as this happens once every 1K jobs or more but its hitting us with integration testing.

Today we are using these 3 in conjuction:
gem 'sidetiq'
gem 'sidekiq-unique-jobs'
gem 'sidekiq-throttled'

Are there any known issues we should be aware of? The specific disspearing jobs we have noticed are only using 2 gems though:

```ruby
class SomeWorker
  include Sidekiq::Worker
  include Sidekiq::Throttled::Worker

  sidekiq_options unique: :until_and_while_executing
  sidekiq_throttle({ concurrency: { limit: 30 } })
end
```

Any ideas?

**Comment by mhenrixon** [comment]
Seams likely that it has something to do with the throttling? Very hard to tell for sure but that would be my guess. If the job has been enqueued and a worker exists for that queue it should be all good.
