### ISSUE TITLE
Job.delete does not remove lock in all circumstances

### ISSUE THREAD

**Issue by ewalk153** [mhenrixon/sidekiq-unique-jobs#205]
I'm using the `until_and_while_executing` (my case may or may not be related to this job type).

For this sample job:
```ruby
class Sample
  include Sidekiq::Worker
  sidekiq_options unique: :until_and_while_executing

  def perform(arg1)
    Rails.logger.info("Job called with #{arg1}")
  end
end
```

When I delete the job, the lock fails to be removed. For example:
```ruby
k = Sample.perform_async "hi"
puts "Next queue return #{Sample.perform_async 'hi'} (nil means locked)"
j = Sidekiq::Queue.new.find_job k
j.delete # this should remove the lock
puts "Next queue return #{Sample.perform_async 'hi'} (nil means locked)"
```

I've looked into `sidekiq-unique-jobs` and changing https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib/sidekiq_unique_jobs/sidekiq_unique_ext.rb#L95
from `unlock(item)` to `SidekiqUniqueJobs::Unlockable.unlock(item)` resolves the problem for me.

Would you like me to submit a pull request? How can I help resolve this problem?

**Comment by mhenrixon** [comment]
Check version 5.0.0 if this is still an issue?

**Comment by ewalk153** [comment]
Sounds good, I'll check it out.
