### ISSUE TITLE
version 4.0.19

### ISSUE THREAD

**Issue by dmkc** [mhenrixon/sidekiq-unique-jobs#206]
Hi @mhenrixon. Any chance of the new version release or should I just pin to a git commit? Would really love to have https://github.com/mhenrixon/sidekiq-unique-jobs/pull/200

**Comment by mhenrixon** [comment]
I don't want to cut another broken gem and since some tests are failing I want to fix those first just to be sure. 

Currently recommending a use at your own peril for the master branch. Using a commit sha isn't a bad idea if you find one that is working for you :)

**Comment by mhenrixon** [comment]
Released version 5.0.0
