### ISSUE TITLE
Util.del Redis::CommandError: ERR syntax error

### ISSUE THREAD

**Issue by untoldone** [mhenrixon/sidekiq-unique-jobs#207]
I run:

    k = SidekiqUniqueJobs::Util.keys[0]
    SidekiqUniqueJobs::Util.del k

And get

    Redis::CommandError: ERR syntax error
	from /usr/local/bundle/gems/redis-3.3.2/lib/redis/client.rb:121:in `call'
	from /usr/local/bundle/gems/redis-3.3.2/lib/redis.rb:2467:in `block in _scan'
	from /usr/local/bundle/gems/redis-3.3.2/lib/redis.rb:58:in `block in synchronize'
	from /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /usr/local/bundle/gems/redis-3.3.2/lib/redis.rb:58:in `synchronize'
	from /usr/local/bundle/gems/redis-3.3.2/lib/redis.rb:2466:in `_scan'
	from /usr/local/bundle/gems/redis-3.3.2/lib/redis.rb:2487:in `scan'
	from /usr/local/bundle/gems/redis-3.3.2/lib/redis.rb:2509:in `block in scan_each'
	from /usr/local/bundle/gems/redis-3.3.2/lib/redis.rb:2508:in `loop'
	from /usr/local/bundle/gems/redis-3.3.2/lib/redis.rb:2508:in `scan_each'
	from /usr/local/bundle/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/util.rb:29:in `each'
	from /usr/local/bundle/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/util.rb:29:in `to_a'
	from /usr/local/bundle/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/util.rb:29:in `block in keys_by_scan'
	from /usr/local/bundle/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq-unique-jobs.rb:72:in `block in connection'
	from /usr/local/bundle/gems/sidekiq-4.2.9/lib/sidekiq.rb:95:in `block in redis'
	from /usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
    ... 4 levels...
	from /usr/local/bundle/gems/sidekiq-4.2.9/lib/sidekiq.rb:92:in `redis'
	from /usr/local/bundle/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq-unique-jobs.rb:72:in `connection'
	from /usr/local/bundle/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/util.rb:76:in `connection'
	from /usr/local/bundle/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/util.rb:29:in `keys_by_scan'
	from /usr/local/bundle/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/util.rb:11:in `keys'
	from /usr/local/bundle/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/util.rb:16:in `block in del'
	from /usr/local/bundle/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/util.rb:56:in `timed'
	from /usr/local/bundle/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/util.rb:16:in `del'
	from (irb):8
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

Using Redis 3.2.6.

Also, the reason I'm looking at this is that I've somehow ended up with a lock on a job that no longer exists.

**Comment by mhenrixon** [comment]
Fixed in version 5.0.0
