### ISSUE TITLE
Unclear docs / examples for unique_args

### ISSUE THREAD

**Issue by untoldone** [mhenrixon/sidekiq-unique-jobs#211]
There's a lack of docs for what is passed as parameters to the `:unique_args` lambda / method. What is args? what are the methods on args? In the example, there are three parameters to the method, but what are they supposed to be?

**Comment by untoldone** [comment]
Btw, this is almost certainly https://github.com/mhenrixon/sidekiq-unique-jobs/issues/193#issuecomment-281599779

**Comment by mhenrixon** [comment]
The args will always be an array of arguments that are passed to the unique_args method. That is just how everything is wired. Even if your job has zero or more arguments the args will be an array.
