### ISSUE TITLE
deprecation warnings with redis-namespace 2.0

### ISSUE THREAD

**Issue by axlekb** [mhenrixon/sidekiq-unique-jobs#212]
Noticed these deprecation warnings when I updated some related Gems.  Just wanted to log the issue!  Don't have the time to figure out the source right now.

```
redis (3.3.3)
redis-actionpack (5.0.1)
redis-namespace (1.5.3)
redis-rack (2.0.0)
redis-rails (5.0.1)
redis-store (1.2.0)
```
> Passing 'info' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /Users/alexb/.rvm/gems/ruby-2.3.3/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq-unique-jobs.rb:65:in `block in redis_version')

> Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /Users/alexb/.rvm/gems/ruby-2.3.3/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/scripts.rb:27:in `block in call')

**Comment by tconst** [comment]
Can be silenced by using the `Redis::Namespace#redis` client directly for these admin commands.

In [scripts.rb#L27](https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib/sidekiq_unique_jobs/scripts.rb#L27) you could do something like this, though thats probably not a great solution.  Just leaving this here for informational purposes.

```ruby
if defined?(Redis::Namespace) && redis.instance_of?(Redis::Namespace)
  redis = redis.redis
end
```

**Comment by mhenrixon** [comment]
It is strongly discouraged to use redis namespace since some time. Support for this has been dropped completely now.

**Comment by axlekb** [comment]
For anyone that cares, I found the relevant post by @mperham of sidekiq discouraging namespaces:

http://www.mikeperham.com/2015/09/24/storing-data-with-redis/

**Comment by aCandidMind** [comment]
Wouldn't it make sense to drop that code then?
https://github.com/mhenrixon/sidekiq-unique-jobs/search?q=namespace

**Comment by mhenrixon** [comment]
@aCandidMind I'll get it done for the next release! Thanks for following up on that 👍

**Comment by danielricecodes** [comment]
@mhenrixon - I'm still getting this message even using S-U-J 5.0.10.  Should I use the Github version of your gem?  Has this issue been fixed in an official Rubygems release?  Thx.  

Here are my relevent gems and versions:

```bash
~$ gem list redis sidekiq
redis (4.0.1)
redis-namespace (1.6.0)
rspec-sidekiq (3.0.3)
sidekiq (5.0.5)
sidekiq-unique-jobs (5.0.10)
```

**Comment by codener** [comment]
I cannot currently afford to upgrade Sidekiq and thus would not be able to profit from this fix in a new version of this gem, so I worked around this by silencing the deprecation warning.

```
# initializers/sidekiq.rb
ENV['REDIS_NAMESPACE_QUIET'] = 'true' # Disable deprecation warning

# … more Sidekiq-related code here
```
