### ISSUE TITLE
Removing "uniquejobs" hash?

### ISSUE THREAD

**Issue by lephyrius** [mhenrixon/sidekiq-unique-jobs#213]
I noticed that I had a memory OOM error in redis. So I investigated what was causing it and I found that the "uniquejobs" key was extremely large. (like 98% of our redis) 
So... 
Is this a bug? 
Have I misunderstood how this works? Have I broken anything by removing the hash?
Do I need some kind of cleaner because right now it doesn't seem to cleanup by itself?

**Comment by wendelscardua** [comment]
@lephyrius it seems to be related to #200 , and indirectly to #206 , so it should be fixed in the next release (as this fix is yet to be released, I've resigned myself to using the `master` branch version for now - `gem 'sidekiq-unique-jobs', github: 'mhenrixon/sidekiq-unique-jobs'`)

**Comment by mhenrixon** [comment]
We should remove jobs better in version 5.0.0. Feel free to reopen an issue if that is not the case!

**Comment by mhenrixon** [comment]
You can also clear the hash by running `bundle exec jobs expire`
