### ISSUE TITLE
Is it possible to get the Job ID of original job?

### ISSUE THREAD

**Issue by nasa42** [mhenrixon/sidekiq-unique-jobs#217]
`SidekiqWorker.perform_async(1)` usually returns the job-id of scheduled job. However, if the job is already scheduled, `SidekiqWorker.perform_async(1)` on subsequent calls will return `nil`. In latter case, is it possible to get the job-id of _original_ job?

**Comment by mhenrixon** [comment]
To my knowledge that is not an easy task. I mean you could query based on the unique key and possibly get the jid from the hash we use but it would be quite complicated and time consuming.

**Comment by nasa42** [comment]
Thanks for answering.
