### ISSUE TITLE
Missing documentation on activejob usage

### ISSUE THREAD

**Issue by brandonjmckay** [mhenrixon/sidekiq-unique-jobs#221]
I'm wondering if there's a way to pass in `unique:` options for each job in the same way you can per worker.

The example doc only shows setting a default for activejob, is it possible to pass in job specific options for this? What is the syntax?

having `sidekiq_options`, or `options` on the job kill the server when it's starting up.

**Comment by mhenrixon** [comment]
Unfortunately that isn't possible. ActiveJob is too simple. See https://github.com/mperham/sidekiq/wiki/Active-Job for more information.
