### ISSUE TITLE
String arguments not seen as unique 

### ISSUE THREAD

**Issue by dan987** [mhenrixon/sidekiq-unique-jobs#222]
Race conditions using `unique: while_executing` and unique and using `unique: until_and_while_executing`.   
Only happens when using long string IDs as unique arguments, like this one ... 

 `"unique_args" => ["DFmBC7dLRBir1jQY0cLgtg"],`

**Comment by mhenrixon** [comment]
Please provide a more complete example.

**Comment by mhenrixon** [comment]
@dan987 I'd love to help but I need something more to go on. What does your worker class look like? The arguments are always an array when it comes from sidekiq.

**Comment by dan987** [comment]
@mhenrixon thanks so such! the issue has become deprioritized as it is solved in most cases.  Not 100% sure why but will be revisiting this again soon.  Closing the issue for now.
