### ISSUE TITLE
Lock remains when running with Sidekiq::Testing.inline!

### ISSUE THREAD

**Issue by kbaum** [mhenrixon/sidekiq-unique-jobs#23]
When running within Sidekiq::Testing.inline! mode, my jobs seemed to be forever locked.  I believe the reason is that when running within inline mode, the server middleware is not run.

I am thinking there should be a way to disable uniqueness when running within inline mode.

thx!

**Comment by zauzaj** [comment]
@kbaum could you please provide this gist once again, as the link is broken?  I would like to see how you solve this. Thanks
