### ISSUE TITLE
Deprecated Documentation

### ISSUE THREAD

**Issue by federicomoyamartin** [mhenrixon/sidekiq-unique-jobs#246]
Hi guys!

It seems like the documentation is not updated to the latest release. I figured it out the hard way, trying to set the lock expiration time.  The right way to set the lock expiration time is:
`sidekiq_options run_lock_expiration: 2 * 60 # 2 minutes`

As it is shown here: https://github.com/mhenrixon/sidekiq-unique-jobs/tree/v5.0.10
Different to what is shown on the documentation. 

Regards &thanks for the gem it is really useful !!

**Comment by mhenrixon** [comment]
Thanks, I've updated the README.
