### ISSUE TITLE
Difference between :until_and_while_executing vs :until_executed is not clear

### ISSUE THREAD

**Issue by ragesoss** [mhenrixon/sidekiq-unique-jobs#249]
I've reviewed the README several times, and I'm still not clear on what the difference is between `:until_and_while_executing` and `:until_executed`.

They seem like they mean the same thing: the job is locked — with duplicates being discarded — from the time it first gets added to a queue until the time it has finished being processed.

**Comment by lagr** [comment]
I was as confused as you are, but I think the [old readme](https://github.com/mhenrixon/sidekiq-unique-jobs/blob/d67b862c9f004db2370c7e1ac222f2a7045ab57e/README.md) highlights the difference a bit better than the current one:

> This lock is exactly what you would expect. It is considered unique in a way until executing begins and it is locked while executing so what differs from UntilExecuted?

> The difference is that this job has two types of uniqueness:

> It is unique until execution
It is unique while executing
That means it locks for any job with the same arguments to be persisted into redis and just like you would expect it will only ever allow one job of the same unique arguments to run at any given time but as soon as the runtime lock has been acquired the schedule/async lock is released.

I interpret this as "While you _cannot_ enqueue a duplicate `job A'` while `job A` is _either enqueued or running_ with `:until_executed`, with `:until_and_while_executing ` you _can_ enqueue `job A'` while `job A` is running – as long as `job A` is no longer enqueued."

With other words, there are two locks at `until_and_while_executing` which are set at the same time when a job is enqueued, but the uniqueness constraint on the queue is lifted as soon as the job leaves the queue.

**Comment by ragesoss** [comment]
Thanks! I guess part of the updated description got accidentally cut out or something.

**Comment by mhenrixon** [comment]
Sorry about that, the README is on my todo list to update.

**Comment by lagr** [comment]
Thanks for investing your time in this useful piece of code @mhenrixon!

**Comment by ragesoss** [comment]
Yes, thanks!

**Comment by mhenrixon** [comment]
I've updated the readme. I hope it makes more sense how I word it since the recent changes. Please let me know if not.

**Comment by myxoh** [comment]
Apologize if redundant but neither the README nor the explanation helped me where immediately obvious to me - so leaving the explanation as I understood it:

The job A is called twice (A1, and A2):

until_executed: You cannot enqueue Job A2 until Job A1 finishes processing.

until_and_while_executing You cannot enqueue A2 until A1 is STARTS for processing.
You can enqueue Job A2 as soon as Job A1 is picked up for processing **BUT** it will not be picked up until job A1 completes (which guarantees you always run A2 if you need to - but you don't unnecessarily queue A2 if A1 is not yet processed).


So:

Job A1 is on the queue (not yet processed) - this is what happens with Job A2:

<table>
<tr>
 <td> 
 <td> Can be enqueued
 <td> Will be picked up by the worker
<tr>
 <td> Until executing
 <td>No
 <td>Yes* - but in practice NO as it won't be enqueued

<tr>
 <td>Until and while executing
 <td>No
 <td>No
<tr> 
 <td>Until executed

 <td>No
 <td>Yes* - but in practice NO as it won't be enqueued

</table>

_______


Job A1 is being processed- this is what happens with Job A2:

<table>
<tr>
 <td> 
 <td> Can be enqueued
 <td> Will be picked up by the worker
<tr>
 <td> Until executing
 <td>Yes
 <td>Yes

<tr>
 <td>Until and while executing
 <td>**Yes**
 <td>**No**
<tr> 
 <td>Until executed
 <td>**No**
 <td>**Yes* - but in practice NO as it won't be enqueued**
</table>


_______


Job A1 is done being processed this is what happens with Job A2:

<table>
<tr>
 <td> 
 <td> Can be enqueued
 <td> Will be picked up by the worker
<tr>
 <td> Until executing
 <td>Yes
 <td>Yes

<tr>
 <td>Until and while executing
 <td>Yes
 <td>Yes
<tr> 
 <td>Until executed
 <td>Yes
 <td>Yes
</table>


______

This is how we are using them in practice:
- We use`until_executed` when we just want to avoid a job being re-processed but don't care that the job is run with the latest context (say the job reads from the database, and an API - `until_executed`)
In our case we do this when say - this is traggered by a user action with feedback (like a user presses a manual "sync" button)
- We use `until_and_while_executing` when we want to guarantee we always have the latest data (say, as a response to a webhook or event that changes context) - we only need to guarantee this runs ONCE on the latest context.
- We use `until_executing` for potentially long-running jobs where we don't care if they run twice, but we do want to avoid them being accidentally duplicated - say, from a cron-job or webhook performing a non-critical task where you are trying to avoid clogging the queue => we rarely use these
