### ISSUE TITLE
Non-unique jobs can be added even when `sidekiq_options unique: :until_executed`

### ISSUE THREAD

**Issue by USvER** [mhenrixon/sidekiq-unique-jobs#251]
`ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]`
```
sidekiq (5.0.4)
sidekiq-unique-jobs (5.0.10)
```
job defined as
```
class UpsertCollectionWorker
  include Sidekiq::Worker
  sidekiq_options unique: :until_executed
```

Any ideas?

**Comment by mhenrixon** [comment]
Do you need some configuration for unique arguments maybe?

**Comment by USvER** [comment]
@mhenrixon i didn't `require 'sidekiq-unique-jobs'`, such an obvious thing to do, but i've read readme numerous times and didn't found this is a requirement. Would be great to update readme.
Thanks.
