### ISSUE TITLE
Multiple non-unique jobs with until_executed?

### ISSUE THREAD

**Issue by soundasleep** [mhenrixon/sidekiq-unique-jobs#255]
I have a slow-running job that takes 10-20 mins. This job is enqueued every 5 minutes through another process through `worker_class.perform_async(args)`.

I have set the job to be unique until_executed:

```ruby
module UniqueJob
  extend ActiveSupport::Concern

  included do
    sidekiq_options unique: :until_executed,
        log_duplicate_payload: true
  end

  class_methods do
    # none
  end
end

class CryptopiaExchangeWorker
  include UniqueJob

  # ...
end
```

This morning I came to see the Sidekiq process list was full of duplicate jobs:

![sidekiq list blurred](https://user-images.githubusercontent.com/3889656/36230705-2253416c-1240-11e8-91c7-ea24a1261e50.png)

I thought that `until_executed` would explicitly prevent this situation from happening.

Could it be related to `lock_expiration` being only 5 minutes?

```yml
# config/sidekiq.yml
:run_lock_expiration: 300 # 5 minutes
```

**Comment by tmlee** [comment]
+1 Facing similar issue 
my configuration is as follows

```
unique: :until_executed,
lock_expiration: (60 * 60) * 8760
```

**Comment by mhenrixon** [comment]
Which version of sidekiq and unique jobs are you using?

**Comment by soundasleep** [comment]
I'm on sidekiq-unique-jobs (5.0.10) and sidekiq (5.1.1).

**Comment by mhenrixon** [comment]
Check out `v6.0.0.rc1` @soundasleep @tmlee. Version 6 won't have this problem and it will take care of the upgrade automatically.

Keep an eye out on the README and CHANGELOG for more information about the changes.
