### ISSUE TITLE
Duplicate jobs getting created

### ISSUE THREAD

**Issue by rept** [mhenrixon/sidekiq-unique-jobs#257]
I have this code:

```
class SidekiqJob
  include Sidekiq::Worker
  include Sidekiq::Status::Worker
  sidekiq_options queue: :default, retry: false, unique: :until_and_while_executing
end
```

```
class CheckAlertsJob < SidekiqJob
  def perform
    AlertType.where("coalesce(condition) <> ''").each do |alert_type|
      alert_type.check_for_alerts
    end
  end
end
```

There is any task running (CheckAlertsJob) and still new jobs are being queued.  What is wrong?

![image](https://user-images.githubusercontent.com/1388221/36782749-2b5f2b60-1c7a-11e8-8fb4-e50f25544152.png)

**Comment by ragesoss** [comment]
Maybe the locks are expiring? By default, the unique lock only lasts for 30 minutes. See #250 .

**Comment by kammerer** [comment]
I encountered the same/similar issue. Duplicate jobs are being run for `:while_executing` and `:until_and_while_executing` (I verified that jobs are actually run in parallel).

* sidekiq-unique-jobs 5.0.10
* sidekiq 4.2.10
* ruby 2.4.1
* redis 3.0.6

**Comment by mhenrixon** [comment]
@kammerer could you try the master branch? You can't use the master branch with `Sidekiq::Testing` though.

**Comment by mhenrixon** [comment]
Version 6 won't have this problem and it will take care of the upgrade automatically.

Keep an eye out on the README and CHANGELOG for more information about the changes.
