### ISSUE TITLE
undefined method `get_sidekiq_options' for "MyScheduledWorker":String 

### ISSUE THREAD

**Issue by girak** [mhenrixon/sidekiq-unique-jobs#27]
Our Sidekiq redis instance is shared among multiple services.
So workers are available on one of the repo while not on the others.

When a scheduled or retried job is being consumed by the sidekiq poller running on another service, we need to to safely re-enqueue the task without exception.

Currently Sidekiq does re-enqueue jobs without the worker class without issue, but apparently the unique jobs middleware is not accounting for this case.

I have workaround the issue with a monkey patch, but an official fix is much appreciated.  Thanks for the hard work!

**Comment by pencilcheck** [comment]
Still getting this in 3.0.11 when running the be_unique example of `rspec-sidekiq`
