### ISSUE TITLE
Locking with retries

### ISSUE THREAD

**Issue by florrain** [mhenrixon/sidekiq-unique-jobs#289]
Hello,

The latest version does not seem to keep the lock after an exception is raised from a worker. Is that on purpose, and if so is there a way to keep the lock and release it only if the job has successfully run in a `:until_executed` lock type for example?

Thanks

**Comment by mhenrixon** [comment]
Just let me clarify, you are referring to the `v6.0.0.rc5` version right @florrain? That is not how I intended it to work, it might be that my tests miss the case when the lock yields and an error is raised in the worker. I'll see if I can find out what is going on.

**Comment by mhenrixon** [comment]
Found the problem and will fix it and release a new gem version in half an hour or so.

**Comment by mhenrixon** [comment]
@florrain fixed in `v6.0.0.rc6`
