### ISSUE TITLE
Making the GEM compatible with Ruby < 2.3

### ISSUE THREAD

**Issue by florrain** [mhenrixon/sidekiq-unique-jobs#291]
Hey @mhenrixon 

I would like to use the latest version in a Ruby 2.1 application. Loading the GEM with that version does not work because of the new safe navigation operator `&.` in the BaseLock class. There's also the use of the `Integer#positive?` that was added in 2.3 that makes the client middleware to explode.

I personally don't think helper methods should prevent the usage of your GEM, would you accept a PR to fix those? And enforcing the Ruby version in the gemspec to be `>= 2`?

If you know of other references to recent Ruby methods that I can add to that PR that would be helpful as well.

Thanks

**Comment by mhenrixon** [comment]
Please go ahead! You are so right in that the helper methods used shouldn’t prohibit the gem from being used. 

Check the Sidekiq requirements though. I think in later Sidekiq versions 2.1 might not be usable.

**Comment by florrain** [comment]
Great will have that PR up hopefully later today or early next week. Good idea, will double check on that 👍

**Comment by florrain** [comment]
Another question for you -- do you have an estimated release date for the final v6?

**Comment by mhenrixon** [comment]
I was hoping to get some people to test it out first and check that everything is working ok. Any time someone suggests everything is working as advertised I'll cut a final v6.0.0.

The gem has been installed a few times now and since I haven't had that many complaints I'd say it is pretty fine for release.

**Comment by mhenrixon** [comment]
I'm closing this for now, ping me on gitter if you need any help with the Ruby 2.1 work.
