### ISSUE TITLE
Unique Job not work while play with crontab

### ISSUE THREAD

**Issue by laoshucheng** [mhenrixon/sidekiq-unique-jobs#294]
**Describe the bug**
1. here is my uniq job:
``` ruby
class TestJob
  include Sidekiq::Worker

  sidekiq_options unique: :while_executing
  sidekiq_options :retry => false

  def perform
    puts "start #{self.class}(job id: #{self.jid})"

    sleep(100)

    puts "end #{self.class}(job id: #{self.jid})"
  end # def perform
end
```

2. and here is my crontab file:
```bash
* * * * * /bin/bash -l -c 'cd /Users/tonyrisk/work/test_uniq_job && bundle exec bin/rails runner -e development '\''TestJob.perform_async'\'' >> /Users/tonyrisk/work/test_uniq_job/log/cron_log.log 2>> /Users/tony/work/test_uniq_job/log/cron_error_log.log'
```
This will trigger TestJob every minute

**Expected behavior**
The second job will perform when first job is done

**Current behavior**
The second job performed while first job is doing

**Sidekiq Output**
![image](https://user-images.githubusercontent.com/3971407/42873133-fe4b63fa-8ab0-11e8-953d-4929f9501522.png)

Red Rectangle is first Job
Yellow is Second

**Comment by mhenrixon** [comment]
Which version of the gem are you using?

**Comment by laoshucheng** [comment]
sidekiq (5.0.5)
sidekiq-unique-jobs (5.0.10)

**Comment by mhenrixon** [comment]
Could you try `v6.0.0.rc6` instead? Version 5 is not working very well.

**Comment by laoshucheng** [comment]
OK, Let me have try

**Comment by mhenrixon** [comment]
Keep in mind that the way sidekiq works `while_executing` is only run on the background process that runs the sidekiq jobs. This means any number of jobs will started simultaneously. Only one will actually execute. The others will wait until `lock_timeout` is reached (default is 0 don't wait at all). So what you should see is that the jobs get started but then only the first one completes.

**Comment by laoshucheng** [comment]
What's version of rails that the version 6.0.0.rc2 dependent on?
![image](https://user-images.githubusercontent.com/3971407/42882944-b7f870c0-8acc-11e8-9f5c-ff7d8c7038bf.png)

**Comment by mhenrixon** [comment]
It is the ruby version actually, ruby 2.3 (since ruby 2.2 isn't officially supported anymore I decided to also not support it). The `&.` instruction is a built in ruby way of only calling a method if the object the method belongs to isn't nil. Instead of `obj && obj.method_name` you just do `obj&.method_name`

**Comment by mhenrixon** [comment]
There was a recent discussion about older ruby versions in #291 & #292

**Comment by laoshucheng** [comment]
Thank you very much.

**Comment by laoshucheng** [comment]
Thanks, @mhenrixon . I install 6.0.0.rc6 and patch #291 feature(because we're using
 ruby 2.2.5 in production, upgrade to 2.3 is dangerous without enough test cases). It works! Which means when crontab trigger the job, It won't start at the same time. It's perfect!

But, I find It not same behavior before like this: 
> It looks like multiple jobs are running at the same time but in fact the second job will only be waiting for the first job to finish.

In fact, it looks like the second job is not waiting. It will run and check if first is running, and then end itself(the second job).

![image](https://user-images.githubusercontent.com/3971407/42921292-e3cb18e8-8b4d-11e8-9a10-bdc43161c005.png)

**Comment by mhenrixon** [comment]
It is not the same behaviour indeed. Before v6 unfortunately it didn't work reliably. The way it works now is that you need to specify `lock_timeout: 101` to make the next job to run successfully. Right now with the default value of `lock_timeout: 0` the second process attempts to lock, waits for 0 seconds and then just exists.

Unfortunately there is no way to do this properly. It would be pretty cool if the sidekiq server worked a little like the sidekiq client in that it first checked if a job with those same arguments are already running before popping the job. That is not a good queuing system however.

What I am going to do in the gem for a future release is to have some type of `on_conflict` or `on_duplicate`  configuration where you can decide yourself a strategy to use when a job can't achieve the lock in a timely fashion.

**Comment by laoshucheng** [comment]
I set config of `lock_timeout` ,and it works perfect! Thanks @marclennox . And we plan to upgrade our ruby version as your suggest. :)
