### ISSUE TITLE
Confused with UntilExecuted documenation

### ISSUE THREAD

**Issue by ivanovaleksey** [mhenrixon/sidekiq-unique-jobs#326]
Hello, thank you for the awesome library!

I am going to use it in a project to ensure a uniqueness for slow & long running jobs.
While choosing a proper lock type for my case I noticed that documentation for `UntilExecuted` and `UntilExecuting` about unlocks seems to be the same though as I can see it should be slightly different.

https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib/sidekiq_unique_jobs/lock/until_executed.rb#L7
https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib/sidekiq_unique_jobs/lock/until_executing.rb#L7

As I understand `UntilExecuted` should unlock after worker done it's job. It is also stated [here](https://github.com/mhenrixon/sidekiq-unique-jobs/wiki/Locking-&-Unlocking#when-is-my-lock-released).
Please correct me if I am missing something.

**Comment by mhenrixon** [comment]
Sorry about that, looks like a sloppy paste @ivanovaleksey. I'll get it fixed, the until executing does indeed unlock before yielding to the worker. 

I'm really happy that someone is reading the documentation though :) Means the effort of writing it wasn't all a waste.
