### ISSUE TITLE
Problem when job failed and is retrying

### ISSUE THREAD

**Issue by dareddov** [mhenrixon/sidekiq-unique-jobs#332]
**Describe the bug**

When a job is failed and goes to retry queue, then unique key is not being cleared.

**Expected behavior**

I think, the unique key should be cleared on failing jobs. If I'm wrong, let me know 👍

**Current behavior**

When the job failed and try retry we got an error: 'SidekiqUniqueJobs::Conflict: Item with the key: uniquejobs:a24c05f9d1e2933fc6e32640a3b06b4c:RUN is already scheduled or processing' of course if we use raise for on_conflict parameter.

**Worker class**

```ruby
class SyncReservationsWorker < SidekiqWorker
    sidekiq_options dead: true,
                    on_conflict: :raise,
                    lock: :until_and_while_executing,
                    lock_expiration: 20.minutes,
                    queue: 'queue_sync'

    def perform
      SyncReservations.call
    end
  end
```

**Additional context**

**Comment by mhenrixon** [comment]
This is not a bug it is a feature. Since you ask for uniqueness the gem provides it. If we didn't keep the lock you might end up in a situation where multiple jobs are executed at the same time.

**Comment by skalb** [comment]
I'm seeing a similar issue happen to us after upgrading to version 6.

Is there a short term fix or config change possible here?

For now, I'm thinking of just adding a lock expiration since our jobs aren't long running.

**Comment by mhenrixon** [comment]
@skalb yes that is correct. That was my intention or duplicates would be allowed to run, but I am currently reconsidering this strategy.

**Comment by Benjamin-Dobell** [comment]
I'm on 6.0.6 and also seeing issues with locks never releasing, I'm using:

```
sidekiq_options lock: :until_and_while_executing, on_conflict: :log, retry: false
```

When the job fails due to a raised error, the lock is never released:

```
127.0.0.1:6379> KEYS sandbox:unique*
1) "sandbox:uniquejobs:44bb785c4010287945f03cd7cbc68390:RUN:GRABBED"
2) "sandbox:unique:keys"
3) "sandbox:uniquejobs:44bb785c4010287945f03cd7cbc68390:RUN:EXISTS"
```

Thus all subsequent jobs are skipped with:

```
2018-09-26T12:44:42.166Z 20389 TID-owz24fy29 ProcessModelZipJob JID-4a9c629ed8264193d859eba5 INFO: skipping job with id (4a9c629ed8264193d859eba5) because unique_digest: (uniquejobs:44bb785c4010287945f03cd7cbc68390:RUN) already exists
```

**Comment by Benjamin-Dobell** [comment]
I should probably have noted, my job is specifically not _retrying_. So I think the scope of this issue is slightly larger than indicated in the title of this issue.

**Comment by mhenrixon** [comment]
@Benjamin-Dobell this is a known issue. If you set to `retry: 0` you have less problems. You still need to clean up keys that are moved to the dead queue. See https://github.com/mhenrixon/sidekiq-unique-jobs#cleanup-dead-locks. The suggested solution does not work with `retry: false` for some reason.

**Comment by Benjamin-Dobell** [comment]
> The suggested solution does not work with `retry: false` for some reason.

Thanks for the tip, PR submitted:
https://github.com/mperham/sidekiq/pull/3980

**Comment by mathieujobin** [comment]
> ...  but I am currently reconsidering this strategy.

I think I will downgrade to 5.x until you figure this one out
it really does not work for us

**Comment by chadrschroeder** [comment]
I also think that jobs in the dead queue should never prevent new jobs from being enqueued.

For example, say my worker class has a bug that crashes the job during the `perform` step and sends the job to the dead queue.  Then I deploy a fix and call `perform_async` from the console to try to re-enqueue it.  The behavior in version 5 is to re-enqueue and execute the job.  The behavior in version 6 is:

1. The call to `perform_async` returns a new `jid` instead of returning `nil` which indicates the job has been enqueued.
2. The job doesn't actually run.  I think this is because the `RUN:EXISTS` key is still in place for the dead job and SidekiqUniqueJobs silently exits before yielding to the worker.
3. The job is removed from the Sidekiq queues and the Sidekiq log has "start" and "done" entries that make it look like the job ran.

**Comment by lichtamberg** [comment]
I'm also experiencing this bug, but with version 5.0.10, didn't have time to try out the newest version until yet.

For us it would be absolutely necessary, that a newly enqueded worker performs again, cleaning up the locks manually is major bug for us.

**Comment by mhenrixon** [comment]
This should be greatly improved with #374

**Comment by ramontayag** [comment]
I ended up defining an expiry time that's longer than I expect the job to run, just in case something goes wrong (even the Sidekiq process exiting prematurely). This way, the job will not be blocked forever.
