### ISSUE TITLE
Using a different Redis instance

### ISSUE THREAD

**Issue by alexandrebini** [mhenrixon/sidekiq-unique-jobs#337]
Hi there,

Is there any way of using a different Redis instance for sidekiq-unique-jobs or does it really need to use `Sidekiq.redis`?

Thanks!

**Comment by mhenrixon** [comment]
Would be a bit hard to use a separate instance. Some of what the gem does works with the queues directly using Lua.

**Comment by alexandrebini** [comment]
@mhenrixon Alright, thanks!
