### ISSUE TITLE
Passthrough has been deprecated and will be removed in redis-namespace 2.0

### ISSUE THREAD

**Issue by everaldo** [mhenrixon/sidekiq-unique-jobs#338]
Please, update the gem to remove this warning

Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at $HOME/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/sidekiq-unique-jobs-6.0.6/lib/sidekiq_unique_jobs/scripts.rb:57:in `script_sha')

**Comment by mathieujobin** [comment]
I recently noticed a similar warning got removed after PR #275 got merged.
maybe the method `script_sha` needs similar update

hope this helps

**Comment by pacoguzman** [comment]
I've just reached this problem through:

`redis-namespace` 1.5.2

```sh
Passing 'time' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-unique-jobs-6.0.6/lib/sidekiq_unique_jobs/connection.rb:18:in `block in redis')
```

After upgrade to `redis-namespace` 1.5.3

```sh
Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-unique-jobs-6.0.6/lib/sidekiq_unique_jobs/scripts.rb:57:in `script_sha')
```

So based on the last warning message, I think it cannot be easily solved on `redis-namespace` as it seems it cannot be effectively namespaced, I wouldn't expect `redis-namespace` will remove that warning so I think it needs to be addressed on `sidekiq-unique-jobs`, I'm already working on this to provide a solution.

**Comment by mhenrixon** [comment]
You'd have to give me more information for me to help you on this @pacoguzman @everaldo. That line doesn't provide enough information for me to act.

**Comment by everaldo** [comment]
I'm sorry, @mhenrixon , but it's been a long time since I don't work on this project anymore. But I believe this bug (warning) happens in any project using the gem.

**Comment by mhenrixon** [comment]
Well since Mike won't support redis-namespace neither will I ->   https://github.com/mperham/sidekiq/issues/3366#issuecomment-284270120
