### ISSUE TITLE
lock remains after job not properly finish

### ISSUE THREAD

**Issue by mathieujobin** [mhenrixon/sidekiq-unique-jobs#339]
**Describe the bug**
We have had this issue with one specific job, where the unique lock would remain in redis after the job has crashed or did not finish properly

is this the intended behavior?

**Expected behavior**
the lock should be cleared after the job finish, regardless of the status

**Current behavior**
new jobs gets schedule and are discarded indefinitely

**Worker class**

```ruby
class MyWorker
  include Sidekiq::Worker

  sidekiq_options :retry => false, :backtrace => true, :unique => :while_executing

  def perform(args); raise("I made a mistake"); end
end
```

**Additional context**
I noticed you are talking there was a 30 minutes timeout in the 5.x series which got removed.
but in your readme you seems to be recommending against using lock_expiration/lock_timeout
I am also unsure which one would fit best my use case.

thank you for your help

**Comment by mathieujobin** [comment]
oh, this is exact duplicate of https://github.com/mhenrixon/sidekiq-unique-jobs/issues/332

**Comment by mathieujobin** [comment]
reopening, I'd appreciate some insight as to know if `lock_expiration` or `lock_timeout` could help ?

**Comment by mhenrixon** [comment]
Lock expiration definitely will help. The timeout is just how long we wait for a lock to be achieved

**Comment by mathieujobin** [comment]
thanks
