### ISSUE TITLE
Version 5: Job ID Hash Entries Not Removed if Unique Key Expires

### ISSUE THREAD

**Issue by chadrschroeder** [mhenrixon/sidekiq-unique-jobs#346]
Job ID entries in the `uniquejobs` hash are not removed if the job is picked up after the `unique_expiration` time has passed.

To recreate the issue:

1. Stop Sidekiq.
2. Set up a worker with a test expiration that is verify small like `unique_expiration: 10.seconds`.
3. Submit a job.  This will produce a `uniquejobs:85d...` key and an entry in the `uniquejobs` hash.
4. Wait 10 seconds for the `uniquejobs:85d...` key to expire.
5. Start Sidekiq.

At this point the job run, but the `jid` entry will be left in the `uniquejobs` hash.

The problem appears to have been introduced in [this commit](https://github.com/mhenrixon/sidekiq-unique-jobs/commit/692508a49cf8359fd31df6f0735a580e21b01641#diff-8a8118473dadc34c22a7039e6ec85861) which refactored `unlock_by_key` in a way so that `ensure_job_id_removed` was no longer always called.

I see you have [this commit](https://github.com/TermSync/sidekiq-unique-jobs/commit/f933e3b978ebd38b6b90dbd25971c45af6949f60) which also solves the issue by completely removing the `uniquejobs` hash, but it isn't released yet.  I'm going to submit a PR with a single-object change if you'd be interested in releasing this change as 5.0.11.

**Comment by mhenrixon** [comment]
Released as v5.0.11
