### ISSUE TITLE
getting a crash using lock_expiration on v6.0.6

### ISSUE THREAD

**Issue by mathieujobin** [mhenrixon/sidekiq-unique-jobs#350]
**Describe the bug**
trying to find a solution for #349 
decided to give v6.0.6 another try

and I me hitting a crash using lock_expiration and calling with `perform_async`

```
I am giving 6.0.6 a try again... the lock_expiration makes it crash, ...
```
 "error_message": "no implicit conversion of Fixnum into String", "error_class": "TypeError", "processor": "venuenext-dev-loyalty-i-067aa11d2edb2503c:15812", "failed_at": 1542621305.267033, "error_backtrace": [ "/var/lib/gems/2.3.0/gems/sidekiq-unique-jobs-6.0.6/lib/sidekiq_unique_jobs/timeout/calculator.rb:42:in `+'", "/var/lib/gems/2.3.0/gems/sidekiq-unique-jobs-6.0.6/lib/sidekiq_unique_jobs/timeout/calculator.rb:42:in `lock_expiration'", "/var/lib/gems/2.3.0/gems/sidekiq-unique-jobs-6.0.6/lib/sidekiq_unique_jobs/lock/base_lock.rb:111:in `prepare_item'", "/var/lib/gems/2.3.0/gems/sidekiq-unique-jobs-6.0.6/lib/sidekiq_unique_jobs/lock/base_lock.rb:16:in `initialize'", "/var/lib/gems/2.3.0/gems/sidekiq-unique-jobs-6.0.6/lib/sidekiq_unique_jobs/options_with_fallback.rb:45:in `new'", "/var/lib/gems/2.3.0/gems/sidekiq-unique-jobs-6.0.6/lib/sidekiq_unique_jobs/options_with_fallback.rb:45:in `lock'", "/var/lib/gems/2.3.0/gems/sidekiq-unique-jobs-6.0.6/lib/sidekiq_unique_jobs/server/middleware.rb:24:in `call'",
```

**Expected behavior**
lock should expire 10 minutes after it is being created

**Current behavior**
crash

**Worker class**
https://github.com/mhenrixon/sidekiq-unique-jobs/issues/349#issuecomment-439832576

**Additional context**
Add any other context about the problem here.

**Comment by mhenrixon** [comment]
Fixing the README
