### ISSUE TITLE
Version 6: lets you schedule job with missing arguments

### ISSUE THREAD

**Issue by mathieujobin** [mhenrixon/sidekiq-unique-jobs#351]
**Describe the bug**
when perform as required arguments, sidekiq normally returns an error when calling `perform_async` without any arguments, this is no longer the case with sidekiq_unique_jobs 6.0.6

**Expected behavior**
the `ArgumentError` should be raised in the process calling `perform_async` 

**Current behavior**
jobs is sent to sidekiq to crash.

**Worker class**

```ruby
class MyWorker
  include Sidekiq::Worker
  sidekiq_options lock: :until_executed, queue: :undefault
  def perform(args); end

  def self.unique_args(args)
    # the way you consider unique arguments
  end
end
```

**Comment by mhenrixon** [comment]
This one is interesting, I thought I had tests for this. Would it be possible for you to provide a failing test for this?

**Comment by lairtonlelis** [comment]
Sidekiq never had that behavior. `perform_async` doesn't raise `ArgumentError`, even when called with a different number of arguments. The error actually occurs when the job is executed and `perform` is called.

**Comment by mhenrixon** [comment]
I'm closing this one to stay compatible with Sidekiq.
