### ISSUE TITLE
Pinpointing issues with unique digests not being removed

### ISSUE THREAD

**Issue by ramontayag** [mhenrixon/sidekiq-unique-jobs#353]
I noticed that there are some unique digests that remain even after all the jobs are done running. I'm looking for help -- could you point me to the right direction to figure out what may be causing this?

Scenario:

I'm using this with [sidekiq-cron](https://github.com/ondrejbartas/sidekiq-cron) to enqueue jobs at fairly rapid pace (quickest is every 5 seconds). Sometimes, the jobs take longer than 5 seconds. To avoid enqueuing an ever-growing number of jobs in those scenarios where the job takes longer than 5 seconds, I use this gem.

Here are information about my setup:

- Sidekiq 5.2.2
- SUJ 6.0.6
- Ruby 2.5.0
- Rails 5.1.6
- Redis 4.0.10
- The Sidekiq process isn't prematurely killed (by an OOMKiller, for example)
- Not using redis-namespace
- Using `until_executed` on all these jobs
- No jobs die and raise exceptions (but I have also setup a death handler anyway)

To test the above, I stop all "cron" jobs and wait for the queued jobs to complete. Then, I look at the Unique Digests tab and see some live on. I have seen from two to 30 or so.

Thanks

**Comment by fabioperrella** [comment]
I think I have a similar issue. In production, some jobs are locked forever. Looking at redis, it seems like some keys are not being deleted, example:

```
$ redis-cli keys '*' | grep 55f2f62648809f8b6121715
sidekiq:myapp:uniquejobs:55f2f62648809f8b6121715aa354cc36:RUN:EXISTS
sidekiq:myapp:uniquejobs:55f2f62648809f8b6121715aa354cc36:RUN:GRABBED
```

After removing these keys and running perform again, the job is processed!

**Comment by fabioperrella** [comment]
I'm using the redis-namespace gem. I will try to remove it to see if the problem is resolved.

**Comment by fabioperrella** [comment]
After upgrading from 6.0.6 to 6.0.7 the problem was fixed for me!

**Comment by mhenrixon** [comment]
Yes exactly! Thanks for confirming @fabioperrella, I should go through the rest of the issues and close them too! Close by `v6.0.7`
