### ISSUE TITLE
Strange behavior using strategy "reject" with "until_executed"

### ISSUE THREAD

**Issue by fabioperrella** [mhenrixon/sidekiq-unique-jobs#358]
Using the version 6.0.7, I think it is only possible to use the strategy `on_conflict: :reject` with `lock: :while_executing`.

But I was trying to use it with `lock: :until_executed` and I expected when trying to schedule the same job again, that this jobs would be not enqueued, but it is!

Example (with sidekiq not running):
```
SomeWorker.perform_async(2)
=> "dafed71805e9abfe57344bd7"
SomeWorker.perform_async(2)
=> Rejecting job with jid: eaf279847ccd8e024bd3ab10
=> Adding dead SomeWorker job eaf279847ccd8e024bd3ab10
```

But when looking in sidekiq web http://localhost:3000/sidekiq/queues/worker_medium , the job is enqueued twice, but I expected to see just once (because the second was rejected).

I'm not sure if this is the expected behavior, given the `on_conflict: :reject` only works with `lock: :while_executing` or if it is a bug, given the messages I saw in console.

**Comment by mhenrixon** [comment]
Reject is incompatibel with while executing. It has been documented both in readme and in the wiki. Reject only works from the client. WhileExecuting doesn't perform any locking when the client runs only while the server picks it up for running so this would be expected behavior.

**Comment by fabioperrella** [comment]
> Reject is incompatibel with while executing

I think you wanted to say `is compatible`, ins't it?

@mhenrixon ok, so it is not a bug!

But do you think it would be possible to add a feature to reject the enqueue of a new job which is already enqueued?

Is this a bad idea?

In my app, there is a worker in crontab to retry the jobs which didn't finish and this worker is enqueueing the same job many times if this job is already in sidekiq queue, because there is no way to reject when enqueueing.

**Comment by mhenrixon** [comment]
Sorry, I was confused! 

There isn't really a need to reject jobs when the client middleware runs @fabioperrella. The default behaviour of UntilExecuted is that a lock will be attempted and if a lock can't be achieved the job won't be put on the queue. I can't remember exactly from the top of my head but I think WhileExecuting crashed with time out error in some cases and this allows the job to silently be simply rejected without retry if a job is already executing.
