### ISSUE TITLE
Low quality peace of shit

### ISSUE THREAD

**Issue by mainameiz** [mhenrixon/sidekiq-unique-jobs#360]
I just started an upgrade from v3 to latest version in my project and can't find anything useful from changelog or readme.

---

From [Changelog](https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/CHANGELOG.md#v400)

```
v4.0.0
- 100% breaking changes
```

What was broken between v3 and v4? What was changed?

---

Which parameters are passed to `unique_args` proc/method, just job arguments or worker_class+queue_name+args 

[Here](https://github.com/mhenrixon/sidekiq-unique-jobs/tree/v4.0.18#finer-control-over-uniqueness) `unique_args` method accepts `name`, `id` and `options`. What does it mean? Which `name`? Which `id`? What `options`?

```ruby
  def self.unique_args(name, id, options)
    [ name, options[:type] ]
  end
```

But when you use `unique_args` in real project, it accepts only one parameter - job arguments.

Is it changed between v3 and v4 or not?

---

`unique: true` was removed, but with which mode it must be replaced?

**Comment by mainameiz** [comment]
Could you follow suggestions about changelog written [here](https://keepachangelog.com/en/1.0.0/) and improve the readme file?

**Comment by henrik** [comment]
@mainameiz Wow, that's a very rude issue title. May I suggest you rephrase it?

Please realise that maintainers don't owe you anything. If I was the maintainer, I would go out of my way not to help someone if they expressed themselves this way.

**Comment by jchatel** [comment]
Nice, definitely someone with anger issues. But he probably didn't understand what it meant since he wrote Peace instead of Piece 🤣

**Comment by john-denisov** [comment]
@mainameiz You need to have a *piece* of mind :trollface:

**Comment by mainameiz** [comment]
Ok guys, sorry, I was in rage when I wrote it.
But I really think that this gem has a poor quality and code. I tried to update this gem through several major versions (from 3.x version to 6x) And there was no way to check what was changed. The only way was to read all the code and commits made for a years.

**Comment by richkettle** [comment]
You could have published that and saved the next person. But I wouldn't expect that from someone with the title you gave.

**Comment by henrik** [comment]
😂 Glad that offensive typo was fixed.
