### ISSUE TITLE
Can a duplicate queued job be completely deleted (not moved to Dead)?

### ISSUE THREAD

**Issue by interlinked** [mhenrixon/sidekiq-unique-jobs#369]
I may be misunderstanding how this gem works (which is quite likely :-) ), but I'm wondering if this is possible:

I'd like any queued jobs that are duplicates to simply *disappear*...completely deleted.  Is that possible, or do they have to go into the Dead "queue"?

**Comment by mhenrixon** [comment]
Dead queue is only used by the death handlers. What you are asking for is how it is supposed to work! 🤓

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by interlinked** [comment]
Got it @mhenrixon, thanks.  I guess I was hoping that this gem would prevent duplicate jobs from being queued _at all_.  I coded something like that in the past, but it was messy.

**Comment by mhenrixon** [comment]
Just like you are writing; the job won't end up in the queue at all. It will just be silently dropped if the client middleware finds out the job isn't unique.

**Comment by interlinked** [comment]
Hey @mhenrixon, thanks for the quick responses, by the way...

I just want to flog this "dead horse" one more time.  I forked this repo, and then made the following commit, which removed the code that puts the duplicate job into the Dead Queue: https://github.com/interlinked/sidekiq-unique-jobs/commit/8f4d18fd165243b86ffc28098d4e50468191a87e

Is this something that might be useful as another on-conflict option (if coded cleaner), or is it a "hack" that really doesn't use Sidekiq properly?

**Comment by mhenrixon** [comment]
I really don't want to come off as rude or anything @interlinked but the code you linked to is pointless. If you don't want any conflict resolution you don't have to do anything and the job will just be rejected. on conflict rejected is there for that specific purpose (to move the code to the dead queue.

If you rather just drop the job - don't use a conflict resolution.

**Comment by interlinked** [comment]
Sorry (and thanks for the response).  I thought conflict resolution was required for the gem to work.  That's exactly what I was looking for.  I just didn't understand.

**Comment by jadengore** [comment]
Is this default behavior explained in the docs? I had trouble finding it and didn't realize conflict resolution was optional.

**Comment by mhenrixon** [comment]
>Is this default behavior explained in the docs? I had trouble finding it and didn't realize conflict resolution was optional.

@jadengore it isn’t explained properly in the documentation unfortunately. I’ll see about clarifying that for the next version.
