### ISSUE TITLE
Custom Locks with error

### ISSUE THREAD

**Issue by miguelseguray** [mhenrixon/sidekiq-unique-jobs#392]
Hello,

I define some custom lock and I make the call in your project startup:

```ruby
SidekiqUniqueJobs.configure do |config|
  config.add_lock :my_custom_lock, Locks::MyCustomLock
end
```

```ruby
class MyWorker
  include Sidekiq::Worker
  sidekiq_options lock: :my_custom_lock
  def perform(args); end
end
```

```ruby
gem 'sidekiq', '5.2.7'
gem 'sinatra', require: false
gem 'slim'
gem "sidekiq-cron", "1.1"
gem "sidekiq-status"
gem 'sidekiq-unique-jobs', '6.0.13'
```

but it does not work

```
/root/Proyectos/sidekiq/config/initializers/sidekiq_unique_jobs.rb:4:in `block in <top (required)>': undefined method `add_lock' for #<SidekiqUniqueJobs::Config:0x00562655cb8668> (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.4.1/gems/sidekiq-unique-jobs-6.0.13/lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb:73:in `configure'
        from /root/Proyectos/sidekiq/config/initializers/sidekiq_unique_jobs.rb:3:in `<top (required)>'

```

**Comment by mhenrixon** [comment]
Super weird issue, if you have a look at the bundles source code : `bundle open sidekiq-unique-jobs` does the method exist on the config class then? When not could you check that the version is correct in the source?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jimbodude** [comment]
The custom lock stuff was added post-6.0.13 release, according to git history:
https://github.com/mhenrixon/sidekiq-unique-jobs/compare/v6.0.13...master#diff-a6cab90adb1364866afa90f4744c2cf5

**Comment by mhenrixon** [comment]
I’m that case I will cut a new release tonight.

**Comment by mhenrixon** [comment]
I'm really sorry @jimbodude. Life has been really crazy with PSD2 deadlines, organizing the move to our new home and having two little girls 24 and 7 months old.

I'll get on it right away!

**Comment by jimbodude** [comment]
No worries, I know where you're coming from.

**Comment by mhenrixon** [comment]
Later versions should have this added so closing this issue.
