### ISSUE TITLE
FIFO strategy

### ISSUE THREAD

**Issue by nononoy** [mhenrixon/sidekiq-unique-jobs#415]
Hi. I tried all the strateges, but didn't figure it out. What if I need to handle all jobs in strict order one after another. Job 1 -> Job 2 -> Job 3. Can I do such FIFO without custom locks?

**Comment by mhenrixon** [comment]
That is how it works by default. You are looking for `:until_executed`

**Comment by mhenrixon** [comment]
Oh no wait, the subsequent jobs will just be dropped. You probably have to look at someother gem for that. Think Sidekiq batches can achieve that

**Comment by nononoy** [comment]
Unfortunatelly it not works with reschedule. "Stack level too deep" error if I bump second task when the first one is under processing.
