### ISSUE TITLE
Is Sidekiq 6.0 supported?

### ISSUE THREAD

**Issue by dbackeus** [mhenrixon/sidekiq-unique-jobs#416]
Though support appears implied by the README in that `>= 5.2` is recommended there has been no new release since the Sidekiq 6.0 release so thought it would be apt to ask if 6.0 is officially tested and supported.

**Comment by mhenrixon** [comment]
Should be working fine @dbackeus. Nothing changed in the interface with middlewares, only major difference was that the logging changed but that was tackled a long time ago.

**Comment by dbackeus** [comment]
Thanks for the response 🙏

Feel free to close this or keep it open for other people wondering the same thing.
