### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by zormandi** [mhenrixon/sidekiq-unique-jobs#422]
This is a trivial problem but a very important one.

The documentation says that the option to set the TTL of the lock key is called :lock_ttl but it's actually called :lock_expiration (at least according to the code). If you're using the :until_expired strategy and setting :lock_ttl then your jobs are going to get stuck forever because :lock_ttl has no effect and the default is to not expire the lock key.

Caused quite a bit of a scare for us until we realized what was happening. :)

**Comment by mhenrixon** [comment]
In that case you are viewing the wrong read me. There are links to your version of the readme in the very beginning somewhere.

**Comment by zormandi** [comment]
You're absolutely right, we're using v6.0.13 (which is the latest version) and there's a link in the readme to documentations of older versions, like 6.0.13. Sorry for the confusion.
