### ISSUE TITLE
Timed out warning in rspec

### ISSUE THREAD

**Issue by blarralde** [mhenrixon/sidekiq-unique-jobs#436]
**Describe the bug**
Messages like `2019-10-24T00:13:30.832Z pid=38356 tid=ov5ssjgco uniquejobs=client =uniquejobs:7bfb0aeacb5a27f3f85cc74cfa565eb4 WARN: Timed out after 0s while waiting for primed token (digest: uniquejobs:7bfb0aeacb5a27f3f85cc74cfa565eb4, job_id: f32958f9c6cf8bf6a2f4ea4b)` output all over my tests.

**Expected behavior**
I'd prefer it doesn't.

**Worker class**
```
sidekiq_options unique: :until_executed
```

**Additional context**
Rails 6.0.0
Sidekiq 6.0.1
Sidekiq unique 7.0.0beta2
fakeredis
rspec-rails 4.0.0.beta2
rspec-sidekiq 3.0.3

**Comment by mhenrixon** [comment]
The either set the Sidekiq logger, the sidekiq unique logger to nil or even better: read the README section about testing https://github.com/mhenrixon/sidekiq-unique-jobs#uniqueness. I recommend against testing for uniqueness in your project.

Let me know if you have any questions or feedback on that. I could turn it off automatically but not all projects have a rack or rails env and the default needs to be enabled for when the gem is added.

**Comment by blarralde** [comment]
Thanks @mhenrixon, this did the trick:
```
SidekiqUniqueJobs.configure do |config|
  config.enabled = !Rails.env.test?
end
```
