### ISSUE TITLE
A worker with "While Executing" lock and "Reschedule" strategy is rescheduled forever

### ISSUE THREAD

**Issue by bunyan** [mhenrixon/sidekiq-unique-jobs#457]
**Describe the bug**
A worker with `lock: :while_executing` and `on_conflict: :reschedule` is being rescheduled in a loop after completion.

**Expected behavior**
Usual Sidekiq worker behaviour, i.e. job being removed from queue after execution.

**Current behavior**
"Reschedule" strategy runs after the worker code is executed scheduling it to be run again 5 seconds after completion.

**Worker class**

```ruby
class Job
  include Sidekiq::Worker

  sidekiq_options lock: :while_executing,
                  lock_timeout: 5, 
                  on_conflict: :reschedule

  def perform
    puts 'hello'
    sleep 1
    puts 'bye'
  end
end
```

**Additional context**
I believe the problem is [here](https://github.com/mhenrixon/sidekiq-unique-jobs/blob/136766124c732fc884b266ec29c61100fb022924/lib/sidekiq_unique_jobs/lock/while_executing.rb#L40) - whether the strategy will be called or not relies on the result of the `callback_safely` which by default returns nil. If I add a callback to the worker class like 
```ruby
def after_unlock
  true
end
```
everything works as expected.

**Comment by mhenrixon** [comment]
Which version of the gem are you using @bunyan?

**Comment by bunyan** [comment]
@mhenrixon,
sidekiq-unique-jobs is 7.0.0.beta5
sidekiq is 6.0.1
Ruby version is 2.5.6

**Comment by mhenrixon** [comment]
I'll get it fixed right away @bunyan

**Comment by mhenrixon** [comment]
Will be fixed in beta7 @bunyan. Should be released in 10 minutes or so

**Comment by bunyan** [comment]
Great, thank you @mhenrixon!

**Comment by mhenrixon** [comment]
Try the new version, now I also have a regression test for it!

**Comment by bunyan** [comment]
Works fine now with the beta7 👍🏻
