### ISSUE TITLE
Tasks run once, and then there is no launch

### ISSUE THREAD

**Issue by danilvoe** [mhenrixon/sidekiq-unique-jobs#464]
1. I add a task.
2. It is scheduled
3. When the time comes for repeated execution it does not work, in the logs at this moment the inscription appears - the unique_key: uniquejobs:eb3c5540017ce14b28c087bb550569fb is not locked, allowing job to silently complete

If the tasks are launched through the sidekiq interface, then the launch occurs, but according to the schedule, the task does not start.

If you delete a task from the schedule and re-set them, then they are started, but only once.

worker defined:

```
class InternalProcessWorker
    include Sidekiq::Worker
    sidekiq_options lock: :until_executed, queue: :internal_manager, retry: false, backtrace: true
```

create job:

```
Sidekiq::Cron::Job.new...
if new_job.valid?
                    new_job.save
end
```
what am I doing wrong?  

gem 'sidekiq', '5.2.5'
gem 'sidekiq-cron', '1.1.0'
gem 'sidekiq-unique-jobs', '6.0.15'

**Comment by hiepdinhxxx** [comment]
I have the same issue :( I was bypass this issue by option `on_conflict: :replace`

```
sidekiq_options queue: 'client_financial_info_worker', lock: :until_executing, on_conflict: :replace
```

**Comment by mhenrixon** [comment]
@hiepdinhxxx are you also using sidekiq-cron?

**Comment by mhenrixon** [comment]
@danilvoe I'm not sure if you managed to get past the problem, I'd be interested in learning more about that setup. I've come across some situations with other sidekiq plugins/middleware causing problems for me.

**Comment by danilvoe** [comment]
@hiepdinhxxx 

The worker is now defined:

```
    include Sidekiq::Worker
    sidekiq_options lock: :until_executed, queue: :internal_manager, retry: false, backtrace: true, unique_args: :unique_args

    def self.unique_args(args)
      [ args[0]["id_proc"] ]
    end
```

As far as I remember, after determining the method of checking for uniqueness, the problem disappeared.

**Comment by mhenrixon** [comment]
Closing as the problem seems to have resolved itself. Please see #571 for upgrading to v7.0.1
