### ISSUE TITLE
undefined method `unique_args_enabled=' for #<SidekiqUniqueJobs::Config:0x00007faa65009828>

### ISSUE THREAD

**Issue by anson2590** [mhenrixon/sidekiq-unique-jobs#472]
I am getting an error that says "undefined method `unique_args_enabled='".
It was working till 5.0, I upgraded to 6.0.18 started getting this error when I start rails server. 
can you please help what may be the fix for this

**Comment by mhenrixon** [comment]
I need some more information from you to be helpful. 

Are you for instance using the gem with ActiveJob? If so, I will not be supporting that moving forward. It has proven too hard to maintain a good solution for Activejob. I recommend you turn to using sidekiq directly instead.

**Comment by iainbryson** [comment]
@mhenrixon Hi!  I've the same problem in upgrading 5->6.  For me  it's explicitly in the config block:

```
  SidekiqUniqueJobs.configure do |config|
    config.enabled = true
    config.unique_args_enabled = true
     end
```

I inherited the code so I'm not 100% sure what this was supposed to be doing in the previous version, and whether it's now the default or whether there's another way to get the same semantics.

**Comment by mhenrixon** [comment]
@iainbryson: that configuration option should just be deleted. Make sure it looks like this instead:

```ruby
SidekiqUniqueJobs.configure do |config|
  config.enabled = !ENV['RACK_ENV'] == 'test'
end
```

If you are using ActiveJob, there is no proper supported way to use worker specific configuration. There are some people hacking together solutions that work for them and ActiveJob but nothing officially supported. 

It was too much work since I never used ActiveJob myself.

**Comment by iainbryson** [comment]
@mhenrixon perfect, thanks!

**Comment by anson2590** [comment]
@mhenrixon great thanks for the help, I will do the same.

**Comment by mhenrixon** [comment]
Cool, let me know if you have any other issues. Meanwhile I'll close this ticket then :)

**Comment by anson2590** [comment]
@mhenrixon when I run chef sidekiq instance is not stopping its going infinite, getting this error

`ruby_block[verify sidekiq process is running] action runWaiting for current instance to stop...`

<img width="794" alt="Screenshot 2020-05-13 at 12 36 22 PM" src="https://user-images.githubusercontent.com/30189967/81781568-f4ac3600-9515-11ea-8f97-55a14e1be9a8.png">

**Comment by mhenrixon** [comment]
@anson2590 that is not because of this gem. You'd have to ask the sidekiq guys for help on this one I think.

**Comment by anson2590** [comment]
@mhenrixon sure I will ask them, Thanks for the update
