### ISSUE TITLE
Yanked version

### ISSUE THREAD

**Issue by vitalinfo** [mhenrixon/sidekiq-unique-jobs#480]
what the reason to delete version from the rubygems which is 4 months old?

version 6.0.18

**Comment by mhenrixon** [comment]
I needed to add a post install message that in a specific situation there was a bug preventing locks from being unlocked. 

I just forgot to re-release the gems because it was late and I was exhausted. 

They are all back now with a post install message recommending to either change the configuration or upgrade to a later version.

**Comment by vitalinfo** [comment]
@marclennox I've added workaround to our Gemfile
`gem 'sidekiq-unique-jobs', git: 'https://github.com/mhenrixon/sidekiq-unique-jobs', tag: 'v6.0.18'`

because for us is to risky to update production servers with newer version with the nearest weeks

**Comment by mhenrixon** [comment]
@vitalinfo there isn't any need anymore, the gems have now been re-released. See #478 for more information.

**Comment by mhenrixon** [comment]
Oh, sorry, I must have misread something. Yanks are irreversible, sorry about that @vitalinfo. I was under the impression I could just change the post install message and release it again.

**Comment by gogiel** [comment]
On Rubygems there's version `6.0.20` released. It's not mentioned in the changelog. Which version is current?
Thanks

**Comment by mhenrixon** [comment]
@gogiel it just contains a backport for a v7 configuration option that some people mistook for active in v6. v6.0.19 contains a bug fix for unlocking logs (similar fix as for 6.0.20). Both are 100% safe to upgrade to, I update the changelog now.

**Comment by mhenrixon** [comment]
Unfortunately, I run into rate limits in my script to update the changelog so need to figure that out first.

**Comment by mhenrixon** [comment]
Ok! Changelog is updated as well. Must be a daily limit or something on the github API.

**Comment by danielricecodes** [comment]
> Oh, sorry, I must have misread something. Yanks are irreversible, sorry about that @vitalinfo. I was under the impression I could just change the post install message and release it again.

Yep.  Yanks are yanks 🤦‍♂️

My heroku builds started failing and I had to fix Bundler to the next version to fix the issue.  Yes this is conservative, I didn't want to go too high up and potentially introduce another issue. 6.0.19 is not yanked (as of right now). 

`gem 'sidekiq-unique-jobs', '6.0.19'`

**Comment by mhenrixon** [comment]
Closing because I believe it isn't relevant anymore. Also, see #571 !
