### ISSUE TITLE
Reaper will delete locks for running jobs

### ISSUE THREAD

**Issue by yaoyi** [mhenrixon/sidekiq-unique-jobs#488]
**Describe the bug**
we currently have many long-running jobs, which may take 10 - 60 minutes each, and use until_executed lock, but reaper cleans up locks for running jobs,  and allow same jobs enqueued, and this also blocks the reaping for real orphans

**Expected behavior**
same jobs should not be enqueued after reaping
reaper should not clean up the locks for any running jobs if the lock type is while_executing  or until_executed

**Comment by mhenrixon** [comment]
Oof, I think it is a little more complicated than that. I believe we need to check if the job is checked out by any worker and if so skip cleaning the job. 

Think that’s what is missing.

**Comment by mhenrixon** [comment]
Released as v7.0.15
