### ISSUE TITLE
Reaper doesn't work - lua or ruby

### ISSUE THREAD

**Issue by pavels** [mhenrixon/sidekiq-unique-jobs#498]
Version of gem is >=7.0.0.beta15

I first tried to enable LUA reaper - it reaps running jobs. I have `lock: until_executed`, as soon as the jobs starts being processed by some worker, it's digest get's reaped. So with  reaper enabled, i see `Execution successfully returned 1` in the logs and the digest is gone.

Than i tried ruby reaper - i have just couple of jobs running (but they run very long, like 30 minutes each) - until no job is running, all is fine, but once some job gets executed is see only `Execution timed out` in the logs - it doesn't reap running jobs but most likely because of that timeout.

**Comment by mhenrixon** [comment]
Related to #488. Seems like there is still some adjustments needed for long running jobs.

**Comment by mhenrixon** [comment]
Still having the same problem @pavels ? the PR #493 should have fixed it, curious if it really did or not.

**Comment by mhenrixon** [comment]
Closing and directing to #571. There was another 14 releases of the beta before moving on to v7 no beta. Try v7.0.1.
