### ISSUE TITLE
How do I turn this on for only one job class?

### ISSUE THREAD

**Issue by brandoncc** [mhenrixon/sidekiq-unique-jobs#510]
Thank you for your work on this project. It looks like everything imaginable is configurable!

Unfortunately, I have read the readme three times and I have not been able to figure out how to turn this on for only one job class. I see how to turn it on globally, but not by worker. It is very likely I just haven't wrapped my head around what a lock is and how it works.

Can you provide a basic example of turning on only for one worker job class?

Thanks again!

**Comment by brandoncc** [comment]
It appears that you just add worker configuration, easy enough.

**Comment by mhenrixon** [comment]
Didn't even make it to give you an answer. I will rewrite the documentation for the go live of v7. I also plan on writing some blog articles on how to use it to help people better understand how to wire it up and how I intend people to use the gem.
