### ISSUE TITLE
Infinite loop in ruby reaper

### ISSUE THREAD

**Issue by markiz** [mhenrixon/sidekiq-unique-jobs#515]
**Describe the bug**
https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib/sidekiq_unique_jobs/orphans/ruby_reaper.rb#L154-L165
This loop does not have an exit point.

**Expected behavior**
Reaper can finish.

**Current behavior**
Reaper loops indefinitely and is killed by timeout

**Comment by mhenrixon** [comment]
Fixed and released as `v7.0.0.beta21` @markiz, thanks for the report!

**Comment by markiz** [comment]
@mhenrixon FYI: this also fixes thread leaking, which occurs when ConcurrentRuby::TimedTask times out.

![image](https://user-images.githubusercontent.com/53611/84499411-3538d400-acbb-11ea-951b-e3637a777cbb.png)

Relevant issue here: https://github.com/ruby-concurrency/concurrent-ruby/issues/639

**Comment by mhenrixon** [comment]
Jesus, had no idea! I'll have a look at the related concurrent-ruby issue tonight! Thanks a bunch for sharing that @markiz
