### ISSUE TITLE
The job gets JID and goes to dead right away

### ISSUE THREAD

**Issue by migalenkom** [mhenrixon/sidekiq-unique-jobs#522]
**Describe the bug**
We have one instance with sidekiq and after some time it starts to work incorrectly. We go to console and call ```HeartbeatWorker.perform_async(false, nil)``` , it shows JID and goes to dead right away.
```
HeartbeatWorker.perform_async(false, nil)
=> "72d9a59868d59c268c063780"
```
In logs, I can see 
```
2020-06-25 08:26:29.174996 W [19701:processor] Sidekiq -- the unique_key: uniquejobs:17efb573488d8206c5190fbaaa8931f8 is not locked, allowing job to silently complete
```
![image](https://user-images.githubusercontent.com/9532901/85675613-8b9c0e80-b6ce-11ea-8108-b39a676b85a2.png)

**Expected behavior**
The worker processed after it get JID and it goes to dead only when we have a job in progress with the same args.

**Current behavior**
The worker is not processed it goes to dead

**Worker class**
```ruby
class UniqueWorker
  include Sidekiq::Worker
  sidekiq_options lock: :until_executed, on_conflict: :reject, unique_args: -> (*args) { args }
end

class HeartbeatWorker < UniqueWorker
  sidekiq_options queue: :default, retry: false, backtrace: true
  
  def perform(a, b)
    MyClass.do_some(a, b)
  end
end
```
**Additional context**
Currently, gem version is 6.0.22, also we tried to 7.0.0.beta22 and received the same issue.

**Comment by 0xCCD** [comment]
Same problem for me !

**Comment by dkirilenko** [comment]
I have the same issue! Any ideas?

**Comment by mhenrixon** [comment]
Seems like a problem with generating the lock.

In v7, you can configure `lock_info` which for instance would tell you which arguments are configured for uniqueness. Maybe that will help with debugging the issue?

I don't see anything apparently wrong but I suspect you have a problem with the unique arguments and what actually ends up with the worker somehow.

**Comment by adrianotadao** [comment]
I'm having the same problem. Any solution?

**Comment by mhenrixon** [comment]
@adrianotadao @0xCCD @migalenkom do any of you create one background job from another?

In the original issue description it looks like that is what is going on. To be completely honest, I haven't done a whole lot of experimenting with this. I just assumed it will work as normal. 

The issue description doesn't make clear if this is the case; hence the question.

**Comment by mhenrixon** [comment]
It would be brilliant if someone that is having this problem could follow the instructions in #571 and create a failing example for me using `v7.0.1`. I'll close this for now but I'm here to help (preferably with v7).
