### ISSUE TITLE
delete_by_digest does not work with the msg['unique_digest'] value available in sidekiq_retries_exhausted

### ISSUE THREAD

**Issue by mikesnare** [mhenrixon/sidekiq-unique-jobs#532]
**Describe the bug**
The documentation [here](https://github.com/mhenrixon/sidekiq-unique-jobs#cleanup-dead-locks) says that you can take the value from `msg['unique_digest']` inside the `sidekiq_retries_exhausted` callback and pass that in to `delete_by_digest` to clear the lock.  This is not working for me.

**Expected behavior**
The lock should be cleared.

**Current behavior**
No lock is cleared.  The digest I am getting looks something like `'uniquejobs:22250f64ead6d01005c7db27fbebcd3d:RUN'`.  This digest cannot be used as-is, and I am forced to strip the `':RUN'` suffix from it (or any suffix) in order to make this work.  

**Additional context**
We're using sidekiq-unique-jobs version 6.0.20.

I looked back at the [documentation for this release](https://github.com/mhenrixon/sidekiq-unique-jobs/tree/v6.0.20#cleanup-dead-locks) and it hasn't changed for this case.  What am I missing?

**Comment by mhenrixon** [comment]
For v7 it is now `lock_digest` while for v6 it was `unique_digest`. This move was done to bring consistency to the keys this gem uses. I've updated the README.md with this for v7.  Let me know if you figured it out or not and we can take it from there.

**Comment by mikesnare** [comment]
@mhenrixon But even `unique_digest` wasn't right _as-is_.  I had to write special code to strip the suffix off the string in order to use it.  Was that fixed with the change made in v7?

**Comment by mhenrixon** [comment]
Why do you have to delete the suffix? 

The `:RUN` suffix is used for `while_executing` and the `while_executing` part of `until_and_while_executing`. If you are using the latter you will also delete the lock for the `until` part if your strip the suffix.

It would be helpful to see how you configured your worker

**Comment by mikesnare** [comment]
Simply because it's not working if I don't.  If I take the `unique_digest` value as given and call `delete_by_digest` with it it doesn't allow me to re-enqueue the same job by calling perform_async with the same args.  This was the only way I found to to get it to work.

Here's the config, if this is all you meant:
```ruby
  sidekiq_options queue: :user,
                  lock: :until_and_while_executing,
                  backtrace: true,
                  retry: NUM_RETRIES,
                  on_conflict: :log
```

Maybe I'm misunderstanding something, but I'm not sure what that is.

**Comment by mhenrixon** [comment]
UntilAndWhileExecuting uses two locks. One for when the client pushes the job to the queue (no :RUN suffix) and one for when the sidekiq server process executes the job for you (has a run suffix). The entire point with that is to let them run separately. At the point the key suffixed with :RUN is created, the previous lock (that is missing the suffix) should have been released. 

I'm not saying you are not having a problem, I am saying the solution is wrong. It means the key was not cleared as part of unlocking the first key. By the time the death handler kicks in that lock should have been long gone. Chances are you are (in the future) unlocking another process job that has been pushed to the queue to be executed later.

**Comment by mikesnare** [comment]
I'm not sure.  What I know is that when I was calling `delete_by_digest(msg['unique_digest'])` and then later trying to re-schedule the job, it was failing and would never run again.  I will do some more testing to re-confirm this.

**Comment by mhenrixon** [comment]
@mikesnare, you were right. There was an issue with the code that deleted the RUN key and it tried to add a second `:RUN` suffix (ending up with `:RUN:RUN`). I've fixed all of that for v7 and recommend you give `v7.0.1` a try.

**Comment by mikesnare** [comment]
Nice to be vindicated.  :)  Thanks for the update!
