### ISSUE TITLE
How to disable Reaper

### ISSUE THREAD

**Issue by tanner-rutgers** [mhenrixon/sidekiq-unique-jobs#543]
**Is your feature request related to a problem? Please describe.**

**Using version:** 7.0.0.beta25

How can we disable the reaper altogether? I think this is accomplishable by setting `config.reaper = nil`, but then I get `FATAL` log messages with `2020-10-28T18:22:30.163Z pid=75152 tid=hzk uniquejobs=reaper FATAL: : is invalid for SidekiqUnqiueJobs.config.reaper`

This is required because we're noticing the Ruby reaper appears to be reaping more than we'd expect (hundreds to thousands of unique keys every hour based on the [log output of `BatchDelete`](https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib/sidekiq_unique_jobs/batch_delete.rb#L74), where we would typically only see a small handful of keys stuck after multiple days)

**Describe the solution you'd like**
A clear and easy way to disable the Reaper(s) without errors or error logs, or documentation showing how to do so

**Describe alternatives you've considered**

Lua reaper is not useful for our case as we're consistently processing high volumes through Sidekiq and cannot afford the Redis lock

**Comment by mhenrixon** [comment]
Try v7.0.0.beta26, you should be able to set the reaper to `:none`, `nil` and `false` to turn it off.
