### ISSUE TITLE
Documentation incorrect for `delete_by_digest`

### ISSUE THREAD

**Issue by tanner-rutgers** [mhenrixon/sidekiq-unique-jobs#547]
**Describe the bug**
The documentation [here](https://github.com/mhenrixon/sidekiq-unique-jobs#cleanup-dead-locks) says we can call `SidekiqUniqueJobs::Digests.delete_by_digest(digest)` to clean up dead locks on job death. However, that method appears to be an instance method, not a class method.

**Expected behavior**
I believe the real call should be `SidekiqUniqueJobs::Digests.new.delete_by_digest(digest)`

**Current behavior**
NoMethodError · undefined method `delete_by_digest' for SidekiqUniqueJobs::Digests:Class

**Additional context**

**Version:** `7.0.0.beta25`

**Comment by mhenrixon** [comment]
I think a convenience class method would be a good idea here but I'll look into it

**Comment by mhenrixon** [comment]
Ok, updating README seems like a better option in this case! done in cffe931
