### ISSUE TITLE
Can't add the lock tab o nthe website when there is authentication through devise

### ISSUE THREAD

**Issue by jchatel** [mhenrixon/sidekiq-unique-jobs#561]
Sorry, this may not be anything to do with you, but I'm not sure why adding the authenticate prevents the lock page (& sidekiq web) from displaying.

As I added `require 'sidekiq_unique_jobs/web'` and now this leads to 404 (`No route matches [GET] "/sidekiq/locks"`) eventhough I'm logged in..

```
  require 'sidekiq/web'
  require 'sidekiq_unique_jobs/web'
  authenticate :logon, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
```

If I remove the `require 'sidekiq_unique_jobs/web'`, this works fine, but of course I don't have the lock tab.

If I remove the `authenticate` line and refresh twice, the dashboard reappears, but of course, I do want the authentication on the user.

I tried with beta27 & beta28

```
gem 'sidekiq', '~> 6.1.2'
gem 'sidekiq-scheduler', '~> 2.2.2'
gem 'sidekiq-status', '~> 1.1.4'
gem 'sidekiq-unique-jobs', '7.0.0.beta28'
```

Any idea what is going on here?

**Comment by mhenrixon** [comment]
Hi @jchatel, could you check against the branch `v7/web-with-auth`? I have tested that it works for me, would love some feedback if it works for you too.
