### ISSUE TITLE
Rejected jobs are still displayed as 'Queued' with gem 'sidekiq-status' on /sidekiq/statuses

### ISSUE THREAD

**Issue by jamesst20** [mhenrixon/sidekiq-unique-jobs#564]
** Gems (all latest) **
```
gem 'sidekiq'
gem 'sidekiq-cron', '~> 1.2'
gem 'sidekiq-status'
gem 'sidekiq-unique-jobs', '~> 7.0.0.beta28'
```

** Description **
When I queue multiple jobs and that a lock rejects them, they are removed from the queue and added to processed as expected.

However, when visiting  /sidekiq/statuses which is provided by the gem sidekiq-status, they are still marked as 'queued' excepted for the jobs that are not discarded.

** Expected behaviors **

Set them as completed or remove them

** Current behavior **

Show as queued while they are no longer queued.
<img width="1149" alt="Screen Shot 2021-01-18 at 10 01 53 AM" src="https://user-images.githubusercontent.com/490234/104931316-39755000-5974-11eb-96ea-36665c45a7a7.png">

**Comment by mhenrixon** [comment]
I have my own page for viewing statuses. You can find a `Locks` tab in the Sidekiq Web interface. 

I know nothing about `Sidekiq::Status` so the fastest way to get my help on this would be to give me a failing test case or example where it goes wrong. 

The more details the better. Otherwise, I can't really commit to fixing it. 

Late last year, someone explained really nicely what went wrong with Sidekiq::Apartment and I was able to quickly create a simple fix for their problem.

**Comment by jamesst20** [comment]
Thanks for the fast reply, I can't seem to find the Locks tab you are talking, I will try to look deeper in the documentation.

** Setup **

1. Install Sidekiq, Sidekiq Unique Jobs, Sidekiq Status
2. Setup routing:
 ```require 'sidekiq/web'
require 'sidekiq-status/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
end
```
3. The route /sidekiq/statuses should be working.

** Reproducing error **

Have a worker:

```
class MyWorker
  include Sidekiq::Worker
  include Sidekiq::Status::Worker
  
  sidekiq_options(
    lock: :until_executed,
    lock_args_method: ->(args) { [args.first] },
    on_conflict: :reject
  )

  def perform(name)
    puts "Running job #{name}..."
    at(50)
    sleep 10
    at(100)
    puts "Done..."
  end
end
```

1. Run Rails Server but not Sidekiq
2. Queue MyWorker a few times (let's say 3 times)
3. Run sidekiq
4. Visit /sidekiq/statuses and notice how there is 2 jobs queued and one completed

**Comment by mhenrixon** [comment]
First of all, you might want to add the web extension for this gem as well:

```ruby
require 'sidekiq/web'
require 'sidekiq-status/web'
require 'sidekiq-unique-jobs/web'

Rails.application.routes.draw do
 mount Sidekiq::Web => '/sidekiq'
end
```

**Comment by mhenrixon** [comment]
From my investigation, this is due to the order of the middleware. To avoid confusion and teach people that the order of middleware is super important, I decided to not add the middleware automatically. 

This part deserves to be clear and up to the user. If you try the master branch (or clear your middleware first) you should be able to set everything up and verify locally. 

I added more information about this to the readme.

**Comment by jamesst20** [comment]
@mhenrixon 

Thanks for the fast reply / fixes. I updated to 7.0.0 (non-beta).

I had never heard of the web extension you told me to add in routes. Can't seem to find anything about it. Also, it's giving me this error when I try to boot up the server:

```
/Users/james/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `**require': cannot load such file -- sidekiq-unique-jobs/web (LoadError)**
	from /Users/james/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/james/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
	from /Users/james/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/james/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require'
```

I updated my middleware chain to this

```
Sidekiq.client_middleware do |chain|
  chain.add SidekiqUniqueJobs::Middleware::Client
  chain.add Sidekiq::Status::ClientMiddleware, expiration: 12.hours
end

Sidekiq.server_middleware do |chain|
  chain.add SidekiqUniqueJobs::Middleware::Server
  chain.add Sidekiq::Status::ServerMiddleware, expiration: 12.hours
end
```

but I am still getting the same behavior. 

Sidekiq v6.1.2
sidekiq-unique-jobs v7.0.0 (stable)

**Comment by jamesst20** [comment]
Update, looks like doing the opposite inside middleware worked !

```
Sidekiq.client_middleware do |chain|
  chain.add Sidekiq::Status::ClientMiddleware, expiration: 12.hours
  chain.add SidekiqUniqueJobs::Middleware::Client
end

Sidekiq.server_middleware do |chain|
  chain.add Sidekiq::Status::ServerMiddleware, expiration: 12.hours
  chain.add SidekiqUniqueJobs::Middleware::Server
end
```

Sidekiq turned off, I queued 4 workers that sleeps for 5 seconds. I ran sidekiq and I got instantly this in the ui:

<img width="1053" alt="Screen Shot 2021-01-20 at 7 37 53 AM" src="https://user-images.githubusercontent.com/490234/105175919-8a12b780-5af2-11eb-8331-1fff86e28b89.png">

5 seconds later:

<img width="1036" alt="Screen Shot 2021-01-20 at 7 38 07 AM" src="https://user-images.githubusercontent.com/490234/105175930-8da63e80-5af2-11eb-9412-7fe7f35369f4.png">

Looks like it's all good :) !

**Comment by mhenrixon** [comment]
Yeah sorry, I sloppy pasted the wrong code. There is a section in the README that has been corrected.

**Comment by mhenrixon** [comment]
@jamesst20 `require 'sidekiq_unique_jobs/web'`

**Comment by ArturT** [comment]
Hi @mhenrixon 

I believe the code example from readme is invalid. https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/README.md#sidekiq-status
I tried it and it left multiple jobs with queued status in sidekiq-status web UI (the same as on [screenshot in the first post](https://github.com/mhenrixon/sidekiq-unique-jobs/issues/564#issue-788339801)).

I noticed you said in readme something opposite to the code presented: `The status middleware should run after uniqueness on client and before on server. `.
So I reverted the order of middlewares and now it works fine for me. 

Here is my working config:

```ruby
Sidekiq.configure_server do |config|
  config.client_middleware do |chain|
    chain.add SidekiqUniqueJobs::Middleware::Client
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes
  end

  config.server_middleware do |chain|
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes # default
    chain.add SidekiqUniqueJobs::Middleware::Server
  end

  SidekiqUniqueJobs::Server.configure(config)
end


Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add SidekiqUniqueJobs::Middleware::Client
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes
  end
end
```

**Comment by mhenrixon** [comment]
Dangit @ArturT! I knew I rushed that a bit much. I'll copy your example to the README.md, thanks a bunch for letting me know!

**Comment by mhenrixon** [comment]
Ok, I updated the README again 😶
