### ISSUE TITLE
undefined method 'delete_by_digest' for SidekiqUniqueJobs::Digests:Class 

### ISSUE THREAD

**Issue by Heroturtle** [mhenrixon/sidekiq-unique-jobs#567]
**Describe the bug**
Updated to 7.0.1, added middleware according to Readme and I get:
NoMethodError: undefined method `delete_by_digest' for SidekiqUniqueJobs::Digests:Class 

**Expected behavior**
method defined 'delete_by_digest

**Current behavior**
What happens instead of the expected behavior?

**Worker class**
my sidekiq.rb config:

require 'sidekiq/web'

redis_options = { url: ENV["REDIS_URL"] }

Sidekiq.configure_server do |config|
  config.redis = redis_options

   config.server_middleware do |chain|
    chain.add SidekiqUniqueJobs::Middleware::Server
  end

  config.error_handlers << ->(ex, ctx_hash) { p ex, ctx_hash }
  config.death_handlers << lambda do |job, _ex|
    digest = job["lock_digest"]
    SidekiqUniqueJobs::Digests.delete_by_digest(digest) if digest
  end
end

Sidekiq.configure_client do |config|
  config.redis = redis_options

  config.client_middleware do |chain|
    chain.add SidekiqUniqueJobs::Middleware::Client
  end
end

Sidekiq.logger       = Sidekiq::Logger.new($stdout)
Sidekiq.logger.level = :info
Sidekiq.log_format = :json if Sidekiq.respond_to?(:log_format)
SidekiqUniqueJobs.configure do |config|
  config.debug_lua       = false
  config.lock_info       = true
  config.logger          = Sidekiq.logger
  config.max_history     = 10_000
  config.reaper          = :lua
  config.reaper_count    = 10_000
  config.reaper_interval = 10
  config.reaper_timeout  = 5
end
Dir[Rails.root.join("app", "workers", "**", "*.rb")].sort.each { |worker| require worker }

Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  [user, password] == ["user_name", "password"]
end
```

**Comment by mhenrixon** [comment]
Sorry about that, seems like the documentation was wrong. Should be fixed in 6cb272ca

The correct usage is:

```ruby
SidekiqUniqueJobs::Digests.new.delete_by_digest(digest) if digest
```
