### ISSUE TITLE
redis-namespace asks to use admistrative commands directly

### ISSUE THREAD

**Issue by Wolfer** [mhenrixon/sidekiq-unique-jobs#578]
When Sidekiq configured use redis namespaces like this

```ruby
opts = {
  host:      APP_CONFIG[:redis_host].to_s,
  namespace: REDIS_NAMESPACE
}

Sidekiq.configure_server do |config|
  config.redis = opts
end

Sidekiq.configure_client do |config|
  config.redis = opts
end
```

Deprecated text appears at startup

```
Passing 'info' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /usr/local/rvm/gems/ruby-2.6.3/gems/sidekiq-unique-jobs-7.0.4/lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb:191:in `block in fetch_redis_version')
````

**Comment by Wolfer** [comment]
https://github.com/resque/redis-namespace#administrative-commands

**Comment by mhenrixon** [comment]
I don't really have a solution to that problem @Wolfer. 

For now, I've followed the Sidekiq approach of recommending against namespaces. 

Possibly, I could provide some type of administrative connection for this that the user configure. 

Not sure why they decided to prevent administrative commands. They created a lot of friction with that decision. 

Doesn't seem fair that I as a gem owner should have to provide extra configuration for a user of my gem to be able to fetch the redis version from the server itself. 

I'll have to do some thinking on this topic. I'm hesitant to create custom stuff for redis namespace.

**Comment by mhenrixon** [comment]
You are aware it is considered bad practice with redis namespace right?

I'm not judging, maybe you have a project where that is outside of your control at the moment. 

I thought it worth mentioning at least.

**Comment by Wolfer** [comment]
Yes, i know, but specific of project forces them to be used =(

**Comment by Wolfer** [comment]
I found than Sidekiq provide method redis_info which incapsulate getting redis info correctly. Please, review my PR https://github.com/mhenrixon/sidekiq-unique-jobs/pull/581

**Comment by mhenrixon** [comment]
Released as v7.0.5

**Comment by Wolfer** [comment]
thank you =)
I make same PR in other your gem https://github.com/brpoplpush/brpoplpush-redis_script/pull/20. Please, review its too

**Comment by mhenrixon** [comment]
Version v7.0.6 was just released with an updated dependency @Wolfer
