### ISSUE TITLE
Deprecation warning for redis behaviour change in 5.0

### ISSUE THREAD

**Issue by MichaelM-Shopify** [mhenrixon/sidekiq-unique-jobs#579]
**Describe the bug**
There is a deprecation warning in Sidekiq output complaining about a line of code in sidekiq-unique-jobs 

> Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0.

It references this line:
https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib/sidekiq_unique_jobs/orphans/ruby_reaper.rb#L127

**Comment by mhenrixon** [comment]
Merp, I knew toggling it in the test suite was a bad idea. 

I'll see if I can support another way. Will keep you posted

**Comment by mhenrixon** [comment]
Released as v7.0.5
