### ISSUE TITLE
Reaper: undefined method `delete_suffix' for nil:NilClass

### ISSUE THREAD

**Issue by yaoyi** [mhenrixon/sidekiq-unique-jobs#585]
in ruby reaper:
```ruby
def match?(key_one, key_two)
   key_one.delete_suffix(RUN_SUFFIX) == key_two.delete_suffix(RUN_SUFFIX)
end
```

the key_two `payload[LOCK_DIGEST]` could be nil, which causes the `undefined method delete_suffix for nil:NilClass`

**Comment by mhenrixon** [comment]
Fixed in `v7.0.6` sorry about that, I'll see if I can remember to write a test case for the when I receive a job that isn't unique later but for right now it should fix your problem.
