### ISSUE TITLE
lock_info set to true but no lock info showing up in web ui

### ISSUE THREAD

**Issue by jakesorce** [mhenrixon/sidekiq-unique-jobs#589]
**Describe the bug**
<img width="1231" alt="Screen Shot 2021-04-06 at 1 22 03 PM" src="https://user-images.githubusercontent.com/801470/113766798-18064380-96db-11eb-9427-5877e2263d52.png">

```ruby
SidekiqUniqueJobs.configure do |config|
  config.debug_lua = true # true for debugging
  config.lock_info = true # true for debugging
  config.max_history = 1000 # keeps n number of changelog entries
  config.reaper = :ruby # also :lua but that will lock while cleaning
  config.reaper_count = 1000 # Reap maximum this many orphaned locks
  config.reaper_interval = 10 # Reap every 10 seconds
  config.reaper_timeout = 5 # Give the reaper 5 seonds to finish
end
```

**Expected behavior**
Expected behavior is to have the lock_info show up in the UI so we can debug jobs

**Current behavior**
Lock info does not show up in the UI.

`To use it turn the following setting on: SidekiqUniqueJobs.config.lock_info = true`- I get this message when I look at the locked job

**Worker class**

![Screen Shot 2021-04-06 at 1 23 20 PM](https://user-images.githubusercontent.com/801470/113766937-4552f180-96db-11eb-80d3-e186da8c3d1d.png)

**Additional context**
N/A

**Comment by mhenrixon** [comment]
You have spotted a bug @jakesorce! I vaguely remembering being perplexed about this, will look into it immediately.

**Comment by jakesorce** [comment]
Thank you 🙏🏼

**Comment by Laykou** [comment]
We observed the same issue with the latest (as of today) version of this gem + sidekiq.

**Comment by mhenrixon** [comment]
Released as https://github.com/mhenrixon/sidekiq-unique-jobs/releases/tag/v7.0.9

**Comment by pdkproitf** [comment]
This does not work on version `7.1.5`
In rails console, the configuration show `true`

<img width="507" alt="Screenshot 2021-08-13 at 1 29 06 PM" src="https://user-images.githubusercontent.com/12691828/129309272-61bc8271-b034-45d3-a123-b407c7d06622.png">

In the worker:
```
sidekiq_options queue: :edenred, lock: :until_executed, retry: RETRY_INTERVALS.length, lock_info: true
```

<img width="1251" alt="Screenshot 2021-08-13 at 1 32 36 PM" src="https://user-images.githubusercontent.com/12691828/129309544-912f9cb2-e613-4af4-9548-5a52aedf5081.png">

**Comment by bdarcet** [comment]
Hey @mhenrixon  ! We're facing the same problem on the latest gem release. Anything we should do ? Reopen an issue ?

**Comment by crondaemon** [comment]
Same here with sidekiq 6.2.1 and sidekiq-unique-jobs 7.1.5.

**Comment by mhenrixon** [comment]
Alright, reopening the issue. Looks like I need some more tests somewhere.

**Comment by marciojg** [comment]
Same issue here.

```rb
# config/initializers/sidekiq.rb

SidekiqUniqueJobs.config.lock_info = true
```
**Versions:**
sidekiq (6.2.2)
sidekiq-unique-jobs (7.1.6)

**Comment by abbbe** [comment]
Facing the same issue

    sidekiq (6.2.2)
    sidekiq-unique-jobs (7.1.7)

**Comment by blanchma** [comment]
Still happening in v7.1.8, sidekiq v6.3.1

**Comment by selivandex** [comment]
Still happening in v7.1.25, sidekiq 6.4.2

**Comment by mhenrixon** [comment]
I will have another look at this.

**Comment by mhenrixon** [comment]
I have test coverage for this saying it should be working and when I try it out locally it also works as expected:

<img width="1265" alt="CleanShot 2022-07-25 at 12 46 50@2x" src="https://user-images.githubusercontent.com/106795/180759941-bb489ab3-9831-4e2d-b366-0a18dd1463e5.png">

@selivandex @blanchma can you provide some more information about your setup? Can't seem to replicate the problem.
