### ISSUE TITLE
Locks are not released: seeing 'Might need to be unlocked manually" warnings

### ISSUE THREAD

**Issue by Axxiss** [mhenrixon/sidekiq-unique-jobs#594]
**Describe the bug**
After upgrading to v7. Looks like all locks are not released properly. Seeing thousands of warnings with "might need to be unlocked manually". Which correlates with a steep increase on redis total keys and memory usage

![image](https://user-images.githubusercontent.com/1160874/114161760-b9360980-9928-11eb-8546-b9a0da84ee68.png)

**Expected behavior**
Locks are released automatically

**Current behavior**
Locks are not released automatically.

**Comment by mhenrixon** [comment]
That seems exactly the opposite of what I would expect. Can you share some more details about your setup? Anything out of the ordinary with your setup? Did you configure the server like here: https://github.com/mhenrixon/sidekiq-unique-jobs/blob/fde172b31f3d42d90bb727594d58c21b921dbfaa/README.md#add-the-middleware

Are you using any other Sidekiq middleware? The order of said middleware are paramount to allowing the various keys to be  released properly.

**Comment by Axxiss** [comment]
Yes, it's configured that way, we are using other middlewares. I'll triple check everything and come back to you.

**Comment by mhenrixon** [comment]
@Axxiss Did you sort this one out or is it still something that needs to be looked into?

**Comment by Axxiss** [comment]
I rolled back on Friday to avoid filling up our redis instance, will continue with the investigation during this week.

**Comment by mhenrixon** [comment]
I added some debugging in #595 for your scenario. I'll cut a new release soon with these changes and I was hoping you'd be able to provide some details about your configuration using that. Basically, it should allow you to also see which workers are generating these problems so that you can share that configuration with me.

**Comment by Axxiss** [comment]
Thanks @mhenrixon, this is the next item on my backlog, will get back to it once I wrap up my current topics.

**Comment by mhenrixon** [comment]
@Axxiss, there was a ton of improvements since I last commented. The latest version is [v7.1.1](https://github.com/mhenrixon/sidekiq-unique-jobs/releases/tag/v7.1.0). Was a small bug in v7.1.0 but that was internal stuff only.

**Comment by Axxiss** [comment]
@mhenrixon thanks for the heads up. I'm currently not working on this and is hard to tell when I will pick up again. If it helps to keep your backlog clean, please close the ticket (I can reopen/recreate in the future)
