### ISSUE TITLE
Sidekiq Pro Sharded Web UI Error > 7.0.8

### ISSUE THREAD

**Issue by navied** [mhenrixon/sidekiq-unique-jobs#605]
**Describe the bug**
When using Sidekiq Pro's Web UI Sharded mode, it breaks retrying, and deleting jobs due to this part of the code:

https://github.com/mhenrixon/sidekiq-unique-jobs/blob/61af2aaaf864ffda17238bc547093c988b61d317/lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb#L247

It tries to look for a job that does not exist on the instance that is running the web UI and instead ends up with a NameError.

**Expected behavior**

For the sidekiq web ui not to break

**Comment by mhenrixon** [comment]
Can't really help there since I don't have a sidekiq pro subscription.  

If someone would cover that for me I'd love to better support Sidekiq pro. 

Hard to debug without the code.

**Comment by mhenrixon** [comment]
Perhaps you could provide the stack trace of the entire thing (relevant unique jobs lines only). 

It seems like this is just a weird edge case that could be a problem regardless of Sidekiq Pro or not.

**Comment by navied** [comment]
I can definitely test any patches if you have any ideas where the issue might be! Here is the stack trace:

![image](https://user-images.githubusercontent.com/1896993/118365386-94a60080-b56a-11eb-801c-5a6b99204063.png)

**Comment by mhenrixon** [comment]
Ah ok, I was confused about the PRO part. 

This has nothing to do with Sidekiq Pro. It is a situation for when the worker doesn't exist on where the code is running. 

The place it crashes needs to be handled better. 

I'll write a failing test for this later.

**Comment by mhenrixon** [comment]
@navied could you verify if the linked PR fixes the issue for you? I suspect you are gathering multiple sidekiq processes under a single `Sidekiq::Web`?

**Comment by navied** [comment]
@mhenrixon just gave it a try, looks all good on my side now! Thanks for the quick fix !
