### ISSUE TITLE
Compatibility with unreleased Sidekiq 6.3.0

### ISSUE THREAD

**Issue by teoljungberg** [mhenrixon/sidekiq-unique-jobs#636]
Sidekiq 6.2.2 released an unofficial alias of `Sidekiq::Worker` as `Sidekiq::Job`, with the plan to migrate to use `Sidekiq::Job` going forward after 6.3.0

https://github.com/mperham/sidekiq/blob/237c70fe374142509e031dbbf136d57f43dd4913/lib/sidekiq/job.rb

The old `Sidekiq::Job` that was inside `sidekiq/api` has since been renamed to `Sidekiq::JobRecord`.

**Comment by mhenrixon** [comment]
I'll make the necessary adjustments

**Comment by mhenrixon** [comment]
Released as v7.1.6, I'm considering back-porting it but haven't found the time yet.

**Comment by jasonrudolph** [comment]
> Released as v7.1.6, I'm considering back-porting it but haven't found the time yet.

Thanks for getting this patched up, @mhenrixon. And thanks for all your work on this gem.

If you have time, a backport for the 6.0.x series would be awesome! 😍

**Comment by teoljungberg** [comment]
As sidekiq 6.3.0 hasn't been released yet I haven't given this a whirl, as soon as the release is out I will and then close the issue.

If you @mhenrixon want to do so beforehand, feel free.

**Comment by mhenrixon** [comment]
@teoljungberg actually, it was added already in 6.2.2 which has been released.

**Comment by teoljungberg** [comment]
Aye you're correct @mhenrixon. We're running the new naming as of this morning and it works wonders. Thanks for the quick turn around
