### ISSUE TITLE
sidekiq_options lock conflicts with sidekiq-lock gem lock option

### ISSUE THREAD

**Issue by recurator** [mhenrixon/sidekiq-unique-jobs#669]
Hello,

Gem [sidekiq-lock](https://github.com/rwojsznis/sidekiq-lock) and [sidekiq-unique-jobs](https://github.com/mhenrixon/sidekiq-unique-jobs) use the same option
[sidekiq_options lock: :until_executing](https://github.com/mhenrixon/sidekiq-unique-jobs#locks)
[sidekiq_options lock: { timeout: 1000, name: 'project_status_lock' }](https://github.com/rwojsznis/sidekiq-lock#usage)
 which causes an error: 
`NoMethodError: undefined method to_sym for {:timeout=>10000, :name=>"project_status_lock"}:Hash
Did you mean?  to_s, to_set
/usr/local/bundle/gems/sidekiq-unique-jobs-6.0.13/lib/sidekiq_unique_jobs/options_with_fallback.rb:52:in lock_class'`
because `sidekiq-unique-jobs` does not expect Hash as lock option value which need to be defined as hash in sidekiq-lock.

So far, I have not found a way to make these two gems work together.

**Comment by mhenrixon** [comment]
They should not be used together
