### ISSUE TITLE
Skip reaping when queues are too large

### ISSUE THREAD

**Issue by francesmcmullin** [mhenrixon/sidekiq-unique-jobs#670]
**Is your feature request related to a problem? Please describe.**
This is a follow up to [an observation in #663](https://github.com/mhenrixon/sidekiq-unique-jobs/issues/663#issuecomment-985544467), when sidekiq queues are very long (e.g., more than 2,000 jobs) the reaper can take a very long time to run, more than likely hitting its timeout (depending on config).

**Describe the solution you'd like**
For applications with traffic/activity spikes, sidekiq queues can get very full, but they are eventually emptied. It's fine if reaping is postponed until queues are lower and there's more slack in the system.

**Describe alternatives you've considered**
We could play with the reaper timeout and count settings to try and find a balance such that reaping can continue even under heavy load, but for our use case it's not a problem if reaping is delayed during heavy activity.

**Additional context**
All my observations relate to the ruby reaper, it is possible that the lua reaper has no trouble with big queues

**Comment by mhenrixon** [comment]
Thank you for the issue, I'll do some thinking on this but I will likely not be able to achieve much until after Christmas. 

I am moving my family across Germany on Monday.

**Comment by francesmcmullin** [comment]
Of course! You've helped a huge amount already. I hope the move goes really well. Thank you =)
