### ISSUE TITLE
unique_args_enabled has been deprecated, nothing in readme

### ISSUE THREAD

**Issue by sgringwe** [mhenrixon/sidekiq-unique-jobs#70]
I am getting an error that says ```unique_args_enabled has been deprecated. See readme for information```, but i don't see anything in the readme that mentions it. Is this a bug?

**Comment by mhenrixon** [comment]
Ah! It is currently delegating to config. I'll get the readme updated if it is missing.

**Comment by codebender** [comment]
+1

**Comment by adrianpike** [comment]
:+1:

**Comment by acegilz** [comment]
+1

**Comment by DarthMax** [comment]
:+1:

**Comment by substars** [comment]
In the meantime, here's how to make this warning go away:

```ruby
# was SidekiqUniqueJobs::Config.unique_args_enabled = true
SidekiqUniqueJobs.config.unique_args_enabled = true
```

**Comment by mhenrixon** [comment]
See https://github.com/mhenrixon/sidekiq-unique-jobs#finer-control-over-uniqueness for more info.
