### ISSUE TITLE
concurrent-ruby 1.1.10 spikes volume of jobs

### ISSUE THREAD

**Issue by oneandonlymike** [mhenrixon/sidekiq-unique-jobs#701]
**Describe the bug**
When using `concurrent-ruby` 1.1.10, the gem does not behave as expected. For the application we are implementing in,  after upgrading to `sidekiq-unique-jobs 7.1.16` we started getting alerts about a higher than normal volume of calls going out to a service that was approaching our rate limit. Attempting the upgrade again with `concurrent-ruby` dropped to `1.1.9` had no issues. It looks like the fix applied in https://github.com/mhenrixon/sidekiq-unique-jobs/pull/688 for https://github.com/mhenrixon/sidekiq-unique-jobs/issues/697 has some unexpected consequences. 

**Expected behavior**
Jobs would be unique, allowing for a consistent pattern of calls to hold.

**Current behavior**
Jobs spike in volume, suggesting some non-unique jobs are making it through.

**Worker class**

```ruby
class MyWorker
  include Sidekiq::Worker
  sidekiq_options queue: :default,
    retry: false,
    backtrace: true,
    lock: :until_executed,
    on_conflict: :log,
    log_duplicate_payload: !Rails.env.test?

  def perform(args); end
end
```

**Additional context**
I noticed the upgrade contained separate logic based on the version of `concurrent-ruby` used, so it makes sense that downgrading it fixed it, I haven't looked deep enough to see what could be wrong though.

**Comment by mhenrixon** [comment]
https://github.com/mhenrixon/sidekiq-unique-jobs/pull/702 I wish they would have taken my suggestion and fixed the issue instead of making the issue permanent...

**Comment by mhenrixon** [comment]
Released as v7.1.19

**Comment by oneandonlymike** [comment]
Something seems to still be wonky with the way this gem performs on the newest concurrent-ruby. On the below chart you can see our job patterns get really wonky and don't have the natural hourly drop in volume like they normally do when concurrent-ruby is at `1.1.10`:
![image](https://user-images.githubusercontent.com/38082514/163198485-e73dcd11-e7f6-42a1-ab92-3b75bf94174d.png)

Through my testing this only happens if `concurrent-ruby` is `1.1.10` and `sidekiq-unique-jobs` is `7.1.16` or greater. Curiously it does not occur when `sidekiq-unique-jobs 7.1.15` is paired with `concurrent-ruby 1.1.10`.

**Comment by mhenrixon** [comment]
I hear you, I'll write my own timeout functionality then and hopefully it won't matter which concurrent version you are having. 

Frigging dependencies aye?

**Comment by oneandonlymike** [comment]
Really appreciate that! 

> Frigging dependencies aye?

Haha yup

**Comment by mhenrixon** [comment]
@oneandonlymike see if v7.1.20 works better for you

**Comment by oneandonlymike** [comment]
v7.1.20 seems to have done the trick! Thanks!
