### ISSUE TITLE
DEPRECATION WARNING: default_worker_options is deprecated and will be removed from Sidekiq 7.0 (use default_job_options instead) (called from notify_agents at /Users/hackeron/Development/Tether/timeline/app/models/user.rb:303)

### ISSUE THREAD

**Issue by rgaufman** [mhenrixon/sidekiq-unique-jobs#705]
Latest version throws this deprecation warning:

```
DEPRECATION WARNING: default_worker_options is deprecated and will be removed from Sidekiq 7.0 (use default_job_options instead)
```

**Comment by mhenrixon** [comment]
Yes, it’s coming from sidekiq and shouldn’t be a problem I think but I’ll look into it.

**Comment by mhenrixon** [comment]
If someone could try out the master branch that would be brilliant. 

I did a bunch of renaming of worker to job. Seems that's the way sidekiq is heading.

**Comment by rgaufman** [comment]
Tried master and the deprecation warnings are gone, so far so good! - Will report back if I notice any issues.
