### ISSUE TITLE
Sidekiq::Testing inline detection assumes you're always using inline testing

### ISSUE THREAD

**Issue by ajsharp** [mhenrixon/sidekiq-unique-jobs#71]
The check in `lib/sidekiq_unique_jobs/config.rb` only looks if you're using sidekiq testing, not which method you're using. So, even if you're using sidekiq's fake testing method, sidekiq-unique-jobs still blows with the mock_redis gem. Is this gem necessary in all scenarios?

**Comment by Draiken** [comment]
There is an inconsistency between the testing strategy and the testing connector. The strategy checks `Sidekiq::Testing.inline?` and the connector doesn't. This breaks a all my tests.

All specs on https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/spec/lib/sidekiq_testing_enabled_spec.rb are actually using `MockRedis` too.

I'll be sending a patch fixing this.
