### ISSUE TITLE
Disable logging in Rails testing

### ISSUE THREAD

**Issue by marclennox** [mhenrixon/sidekiq-unique-jobs#727]
I'm getting a lot of log messages when running Rails specs from this gem.  Is there a way to disable these logs in testing?  The only solution I found was to change from the Sidekiq logger to the Rails logger, but in your documentation you don't recommend changing this configuration.

**Comment by mhenrixon** [comment]
My recommendation was more for production environment. 

It is common to disable logging for test environment which is totally fine. 

Perhaps you can configure logging based on which rails environment it is?

**Comment by marclennox** [comment]
Cool thanks.  Is there a way to disable logging entirely with this gem?

**Comment by mhenrixon** [comment]
From the top of my head: no. It seems like a very nice feature to have. 

Perhaps something like:

```ruby
Sidekiq::UniqueJobs.configure do |config|

  config.logger.level = :fatal
end
````

**Comment by marclennox** [comment]
That would work, or alternatively

```
config.logger = nil
```

**Comment by marclennox** [comment]
```
config.logger = Rails.env.test? ? nil : Sidekiq.logger
```

**Comment by mhenrixon** [comment]
I'm not even sure it works without a logger, try it first. Otherwise

```ruby
config.logger = Rails.env.test? ? Logger.new(nil) : Sidekiq.logger
```

Should do the trick, I'll see if I can add a way to just silence logging also.

**Comment by marclennox** [comment]
Perfect, thanks
