### ISSUE TITLE
spammed by `Nothing to delete; exiting` during spec

### ISSUE THREAD

**Issue by masterkain** [mhenrixon/sidekiq-unique-jobs#733]
```
guard_1            | 2022-08-09T15:01:41.726Z pid=1560 tid=au0 INFO: Nothing to delete; exiting.
guard_1            | 2022-08-09T15:01:41.726Z pid=1560 tid=au0 INFO: delete_by_pattern(*, count: 10000) completed in 3ms
```

I'm getting spammed by this on STDOUT (or STDERR?) for each test and I believe it's coming from here https://github.com/mhenrixon/sidekiq-unique-jobs/blob/10d08bdd53dab0b26d260bfa5c445655a56f1e0c/lib/sidekiq_unique_jobs/testing.rb#L129

I have `require 'sidekiq_unique_jobs/testing'` in my `rails_helper.rb`

Any way to suppress this output? thanks

**Comment by mhenrixon** [comment]
See readme about logging in for example rails test environment.

**Comment by mhenrixon** [comment]
https://github.com/mhenrixon/sidekiq-unique-jobs#uniqueness
