### ISSUE TITLE
Incompatibility with Sidekiq 7

### ISSUE THREAD

**Issue by Earlopain** [mhenrixon/sidekiq-unique-jobs#736]
Sidekiq recently released a beta version of their new major release.

https://www.mikeperham.com/2022/09/27/sidekiq-7.0-beta-now-available/
https://github.com/mperham/sidekiq/blob/main/docs/7.0-Upgrade.md
https://github.com/mperham/sidekiq/blob/main/docs/internals.md

The current version of this gem is not compatible with the new version, since there were large amounts of internal changes.

**Comment by mhenrixon** [comment]
Sidekiq 7 unfortunately will require a complete refactor of my gem and I just haven't been able to figure out why. 

Almost every single test fails against sidekiq 7.

**Comment by johntrandall** [comment]
oof. Sounds like this is blocked for now then...

We could always use SideKiq Enterprise, which includes these features natively, rather than this 3rd party SideKiq-Uniq, but SideKiq it is expensive.

**Comment by jpcamara** [comment]
@mhenrixon I am working on changes for compatibility with Sidekiq 7. I'll open a PR with a fix for https://github.com/brpoplpush/brpoplpush-redis_script today or tomorrow, and get at least an in-progress PR for sidekiq-unique-jobs within the next few days.

**Comment by jpcamara** [comment]
> I am working on changes for compatibility with Sidekiq 7. I'll open a PR with a fix for https://github.com/brpoplpush/brpoplpush-redis_script today or tomorrow, and get at least an in-progress PR for sidekiq-unique-jobs within the next few days.

There are some larger architectural decisions that may be made by @mhenrixon in response to the Sidekiq/Redis gem updates, so i'm not actively working on this atm

**Comment by marclennox** [comment]
I'm curious what is the plan for Sidekiq 7 support with this gem?  We've been using this gem with Sidekiq 6 for a while but will likely need to plan for another solution if Sidekiq 7 support is unlikely.  Thanks.

**Comment by mhenrixon** [comment]
All the tests are failing and i simply haven't had the bandwidth to look into it. 

I tried and failed in one branch and haven't had time to look into it.

**Comment by mhenrixon** [comment]
https://github.com/mhenrixon/sidekiq-unique-jobs/pull/751

**Comment by knightq** [comment]
Thank you @mhenrixon, is this going to be closed, then?
I've seen that you merged PR#751 yesterday...

**Comment by slhck** [comment]
@knightq There is still no new release. I'd be happy to test the upgrade though.

**Comment by mhenrixon** [comment]
Currently doing some QA for this

**Comment by knightq** [comment]
Thank you @mhenrixon ❤️: the new version works like a charm!
I think this issue can be closed now.

**Comment by mhenrixon** [comment]
Closing
