### ISSUE TITLE
If a job is deleted from the enqueued list, it's still unique and new jobs can't be added.

### ISSUE THREAD

**Issue by tokenvolt** [mhenrixon/sidekiq-unique-jobs#74]
For example I have a job:
````ruby
class TestJob
  include Sidekiq::Worker

  sidekiq_options queue: 'high',
                  unique: true,
                  unique_args: ->(args) { [ args.first ] }

  def perform(arg)
    # do something
  end
end
````
And calling it:
````ruby
[1] pry(main)> TestJob.perform_async 1
=> "de5ff32394dbcdab2128d5ee"
````
Then if I go to sidekiq web interface and delete it from the enqueued list before it processed, I can't add a new one with the same argument.

````ruby
[2] pry(main)> TestJob.perform_async 1
=> nil
````
I'm pretty sure this is not an expected behaviour. Am I right?

**Comment by vsorlov** [comment]
I faced the same problem

**Comment by smee-dee** [comment]
Same here

**Comment by maxim198307** [comment]
any updates on this pls? Have an issue while testing the worker - cant start unique worker second time even if the first one is removed from queue...perhaps this issue is connected to this

**Comment by mhenrixon** [comment]
Interesting, I wonder if it has to do with the arguments. I'll write some test cases

**Comment by tokenvolt** [comment]
I explored this a little bit and it appears that lock is not cleared after deleting from web UI, because obviously it does not run any middewares, like it does after finishing the job or if the job is failed.

**Comment by crberube** [comment]
Isn't this what sidekiq_unique_ext.rb is supposed to handle? I noticed that the file isn't required anywhere except for its spec. Not sure why that is.

**Comment by mhenrixon** [comment]
So we obviously need to require the file when `sidekiq/api` is required or `sidekiq/web` for that matter.

**Comment by mhenrixon** [comment]
This has been closed for a while.
