### ISSUE TITLE
Usage of sidekiq-unique-jobs with activejob

### ISSUE THREAD

**Issue by matthijsgroen** [mhenrixon/sidekiq-unique-jobs#76]
To use the uniqueness with active job:

```
Sidekiq.default_worker_options = {
   'unique' => true,
   'unique_args' => proc do |args|
     [args.first.except('job_id')]
   end
}
SidekiqUniqueJobs.config.unique_args_enabled = true
```

Maybe you can update the readme for this?

**Comment by acegilz** [comment]
+1

**Comment by mhenrixon** [comment]
Thanks: https://github.com/mhenrixon/sidekiq-unique-jobs#usage-with-activejob

**Comment by ben-toogood** [comment]
👍

**Comment by IanVaughan** [comment]
The readme does not include the `SidekiqUniqueJobs.config.unique_args_enabled = true`, is this required too?

Also, where should this go?

**Comment by abacha** [comment]
but if I dont want to use unique with all my workers?

**Comment by jolim** [comment]
I've come up with a hack. It's flexible, so you can do what you want with this pattern.

With ActiveJob, it compares all jobs by their argument hash, so all jobs are subject to the action (drop/delay). In the configuration lambda, if you make a job unique by adding a uuid to the arguments hash, the job will not be subject to the action.

You can use any information in the jobs hash. The most interesting ones are the `job_class` and the `queue_name`. I've chosen to implement this hack with the latter by putting jobs onto a queue that I've named `unique_jobs`. You can create any queue name you want, or test if the `[<class names>].include? r['job_class']` or whatever else makes you happy.

```
Sidekiq.default_worker_options = {
  unique: :until_executing,
  unique_args: lambda { |args|
    r = args.first.except('job_id')
    r[:make_unique] = SecureRandom.uuid unless r['queue_name'] == 'unique_jobs'
    [r]
  }
}

**Comment by mhenrixon** [comment]
I strongly recommend people to use sidekiq directly and not bother with active job. Why settle for a Fiat when you can drive a Ferrari?

**Comment by vitalinfo** [comment]
@mhenrixon I'm using sidekiq-unique-jobs with activejob with @jolim approach
but, by some reason I have something like memory leak
`uniquejobs` redis-variable has some amount of key-value pairs, but I haven't big part of them in the redis keys at all.
F.e. on local machine I have 15 `uniquejobs` pairs and have only 2 active jobs from this list, on real server 61009 pairs and only 97 active jobs.
could you please give any advice in this case? either how I can prevent this leak, or at least how I can clear `uniquejobs` hash?
thanks

**Comment by EPecherkin** [comment]
This comparison doesn't work here. It is all about a vendor-lock, which it is always bad for a big business

**Comment by sharshenov** [comment]
Here is an implementation for ActiveJob: [activejob-uniqueness](https://github.com/veeqo/activejob-uniqueness)
