### ISSUE TITLE
Redis server v6.0 compatibility

### ISSUE THREAD

**Issue by cgunther** [mhenrixon/sidekiq-unique-jobs#769]
**Describe the bug**
sidekiq-unique-jobs v8.0.2 doesn't seem to be compatible with Redis server v6.0 (but v6.2 seems fine).

**Expected behavior**
sidekiq-unique-jobs test suite should run fine on Redis server v6.0 (as sidekiq seems to support v6.0 fine).

**Current behavior**
Forked test suite fails when forced to run against Redis server v6.0:
https://github.com/cgunther/sidekiq-unique-jobs/actions/runs/4670497802/jobs/8270299999?pr=1

**Worker class**
N/A

**Additional context**
Trying to upgrade my own application to sidekiq v7 & sidekiq-unique-jobs v8 hit failures in CI and traced it to whether we're running Redis v6.0 or v6.2.

Peeking at the commit to introduce sidekiq v7 compatibility, some branches around the redis server version might have been over-eagerly removed, applying the redis server v6.2+ path universally:
https://github.com/mhenrixon/sidekiq-unique-jobs/commit/67732db6d6184516e4dd463764021f9b02d4dee8#diff-8c17d1ad38c9f20f72b049958ad43db6c1d6c6aa9a9c900811b59fc6087c26b5L305
https://github.com/mhenrixon/sidekiq-unique-jobs/commit/67732db6d6184516e4dd463764021f9b02d4dee8#diff-8292b625479ba371900bc81dd91aa4f71e409c96b77e86d0a170470965c8ce94L82

Perhaps those should be restored to maintain compatibility with redis server v6? Or perhaps sidekiq-unique-jobs should loudly enforce a minimum redis server version of v6.2?

**Comment by mhenrixon** [comment]
As per sidekiq requirements: Redis 6.2+ is required:

![image](https://user-images.githubusercontent.com/106795/231718000-5e2929bc-4007-4429-8353-4b4bc0662aa6.png)

**Comment by cgunther** [comment]
I spoke too soon about "working". Tried on another project, CI works on 6.0, but actually booting a sidekiq server fails loudly on 6.0.  I guess CI worked because it never really boots the sidekiq server, and the sidekiq client maybe doesn't enforce the version constraint as loudly, hence enqueueing jobs and fake-draining them was fine for CI to pass.

Hopefully this is helpful for anyone else stumbling on this.
