### ISSUE TITLE
Migrate away from deprecated Redis commands

### ISSUE THREAD

**Issue by agramichael** [mhenrixon/sidekiq-unique-jobs#780]
WIth Sidekiq 7.1, warnings are printed out (due to [sidekiq#5788](https://github.com/sidekiq/sidekiq/issues/5788)).

**Logs**
```bash
[sidekiq#5788] Redis has deprecated the `rpoplpush`command, called at ["***/gems/sidekiq-unique-jobs-8.0.2/lib/sidekiq_unique_jobs/locksmith.rb:315:in `rpoplpush'"]
```

**Comment by eliasfrigard** [comment]
Second this, `rpoplpush` should be replaced with `lmove` as stated in [https://redis.io/commands/rpoplpush/](https://redis.io/commands/rpoplpush/).

**Comment by GabrielaGuedes** [comment]
Hi, I've jut replaced the deprecated command here: https://github.com/mhenrixon/sidekiq-unique-jobs/pull/781
