### ISSUE TITLE
Deprecation Warning: Use of rpoplpush command in Redis

### ISSUE THREAD

**Issue by navidemad** [mhenrixon/sidekiq-unique-jobs#792]
Hello, Team,

We appreciate your work on the sidekiq-unique-jobs gem. We've encountered an issue while using version 8.0.2.
We are using :
- Rails 7.0.5
- Sidekiq 7.1.2
- Redis 7.0.11
- ruby 3.2.2

**Describe the bug**
During normal operations, we noticed a deprecation warning in our logs related to the use of the rpoplpush command in Redis. Here's the relevant log output:

```sh
2023-06-16 12:16:34.050556985 +0200 CEST [worker-1] [sidekiq#5788]
Redis has deprecated the "rpoplpush" command, called at 
["/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-unique-jobs-8.0.2/lib/sidekiq_unique_jobs/locksmith.rb:315:in 'rpoplpush'"]
```

Since Sidekiq 7.1.0:

> Migrate away from all deprecated Redis commands [#5788] Sidekiq will now print a warning if you use one of those deprecated commands.
https://github.com/sidekiq/sidekiq/blob/main/Changes.md#710

**Expected behavior**
The warning suggests that rpoplpush has been deprecated. According to the Redis documentation (as of the time this issue was created), it is recommended to use the rpop and lpush commands in sequence or use the blpop and rpush commands.

As of Redis version 6.2.0, this command is regarded as deprecated.
It can be replaced by [LMOVE](https://redis.io/commands/lmove) with the RIGHT and LEFT arguments when migrating or writing new code.

https://redis.io/commands/rpoplpush/

**Comment by mhenrixon** [comment]
Closed by #781
