### ISSUE TITLE
Release new gem version with "fix replace deprecated rpoplpush w/lmove"

### ISSUE THREAD

**Issue by mario-amazing** [mhenrixon/sidekiq-unique-jobs#795]
Could you add new release to rubygems with [Fix replace deprecated rpoplpush w/lmove](https://github.com/mhenrixon/sidekiq-unique-jobs/commit/b31e80bc5542188573614adfa77a834a7268ccdf) commit?

error: 
```sh
sm_sidekiq | [sidekiq#5788] Redis has deprecated the `rpoplpush`command, called at ["/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-unique-jobs-8.0.2/lib/sidekiq_unique_jobs/locksmith.rb:315:in `rpoplpush'"]
```

TMP solution:
```ruby
gem 'sidekiq-unique-jobs', git: 'https://github.com/mhenrixon/sidekiq-unique-jobs', ref: 'b31e80b'
```

**Comment by Pallinder** [comment]
Please note that there are some pretty substantial changes in master that have not yet been released relating to locking mechanisms, doing the above will include these changes in your installed gem. 

Forking and cherry picking the commit might be safer depending on what locking strategy you are utilizing..

**Comment by mario-amazing** [comment]
How can I see, the commit with the new locking mechanism is a little bit upper then `ref: 'b31e80b'`
<img width="1302" alt="Screenshot 2023-07-06 at 20 12 18" src="https://github.com/mhenrixon/sidekiq-unique-jobs/assets/9537753/11cc2003-1cbe-4271-b294-d0873de3b2df">

**Comment by mhenrixon** [comment]
> How can I see, the commit with the new locking mechanism is a little bit upper then `ref: 'b31e80b'`

https://github.com/mhenrixon/sidekiq-unique-jobs/releases/tag/v8.0.3
