### ISSUE TITLE
Change log level to info rather than warn

### ISSUE THREAD

**Issue by geoffharcourt** [mhenrixon/sidekiq-unique-jobs#80]
Attempting to create a job that isn't unique shouldn't be such an important event that it shows up as a warning in the logs. I think the ability to log the attempts is great, but I think the value isn't there unless you're engaged in a level of diagnosis in which you're checking logs at the `info` or `debug` levels. Could we switch the logging level to be `info`?

Happy to do the PR to make the change if there's agreement.

**Comment by mhenrixon** [comment]
Closed by #81
