### ISSUE TITLE
Should client middleware also be added to the Sidekiq server config?

### ISSUE THREAD

**Issue by gstokkink** [mhenrixon/sidekiq-unique-jobs#803]
Hi,

In the installation instructions, under [`Add the middleware`](https://github.com/mhenrixon/sidekiq-unique-jobs#add-the-middleware), it states the following bit twice, once under the server config and once under the client config:

```
  config.client_middleware do |chain|
    chain.add SidekiqUniqueJobs::Middleware::Client
  end
```

Is this correct? You'd expect client middleware to only be configured on the Sidekiq client, right?

**Comment by mhenrixon** [comment]
That's correct, the server also acts as a client when solving conflicts etc.

**Comment by gstokkink** [comment]
Alright, just checking, thanks for your quick reply!
