### ISSUE TITLE
should respond to `has_valid_sidekiq_options?`

### ISSUE THREAD

**Issue by cl-nandini** [mhenrixon/sidekiq-unique-jobs#822]
**Describe the bug**
Gem Version `'sidekiq-unique-jobs', '= 5.0.10'`

As per the readme, trying to validate options using rspec.

```
#spec/workers/contacts_communication_info_spec.rb
require 'spec_helper'
require "sidekiq_unique_jobs/testing"

RSpec.describe Contacts::CommunicationInfo do
  specify { expect(described_class).to have_valid_sidekiq_options }
end
```

**Expected behavior**
Expected `Contacts::CommunicationInfo` to have valid sidekiq options but found the following problems

**Current behavior**
```
Contacts::CommunicationInfo is expected to have valid sidekiq options
     Failure/Error: specify { expect(described_class).to have_valid_sidekiq_options }
       expected Contacts::CommunicationInfo to respond to `has_valid_sidekiq_options?`
```

**Worker class**

```ruby
module Contacts
  # Worker to call interactor for CommunicationInfo update
  class CommunicationInfo
    include Sidekiq::Worker
    sidekiq_options unique_across_queues: true, queue: 'api_p1', lock: :while_executing, on_conflict: :log

    def perform(contact_id, changed_keys); end

end
```

**Comment by mhenrixon** [comment]
Thank you for the detailed report. Admittedly this is my first attempt at sharing an RSpec matcher/expectation. 

I'll have a look at this.

**Comment by cl-nandini** [comment]
I was using older version of gem.

**Comment by mhenrixon** [comment]
> I was using an older version of gem.

🤣 that is something I would do. I have (more often than I like to admit), spent a day debugging something like that to realize I have like a typo.

**Comment by cl-nandini** [comment]
apologies! if this has consumed your precious time :)
