### ISSUE TITLE
Compatibility with Sidekiq7

### ISSUE THREAD

**Issue by alekgosk** [mhenrixon/sidekiq-unique-jobs#823]
**Is your feature request related to a problem? Please describe.**

Since November 2022, this gem is not compatible with sidekiq7, see: https://stackoverflow.com/a/74574896.

Sidekiq versions published to RubyGems: https://rubygems.org/gems/sidekiq

Error we encountered after upgrading:

```ruby
usr/local/bundle/gems/redis-client-0.19.0/lib/redis_client/command_builder.rb:37:in block in generate': Unsupported command argument type: TrueClass (TypeError)
```

**Describe the solution you'd like**
I would like this gem to be compatible with Sidekiq7.

**Describe alternatives you've considered**
The current workaround is to pin your gem constraints, like this:

```ruby
gem 'sidekiq', '< 7' # 7.0 is not compatible with sidekiq-unique-jobs
gem 'sidekiq-unique-jobs', '~> 7.1'
gem 'redis', '~> 4' # sidekiq requires < 5
```

**Comment by mhenrixon** [comment]
How is it not compatible? I had one company pay for the upgrade and I remember them rolling it out to production and testing it. 

Have you tried version 8 of sidekiq unique jobs?

**Comment by alekgosk** [comment]
Yes, we tried using version 8. 

We used the following gem combinations:

```ruby
  sidekiq-unique-jobs (8.0.3)
  sidekiq-pro (7.1.3)
  sidekiq (7.2.0)
```

Our sidekiq batched jobs, failed with the error I posted above

**Comment by andrew** [comment]
@alekgosk you need to upgrade to 8.0.4 or greater, which fixed that error, see the changelog
