### ISSUE TITLE
Unique jobs sets Sidekiq testing to inline! mode

### ISSUE THREAD

**Issue by assimovt** [mhenrixon/sidekiq-unique-jobs#88]
I am having an issue that as soon as I enable unique jobs for a worker, Sidekiq starts to operate in inline mode, thus requiring Redis connection. I would like to continue using it in [fake mode](https://github.com/mperham/sidekiq/wiki/Testing#testing-worker-queueing-fake). Is it an expected behavior? Here are the versions I use:

    Using sidekiq 3.3.4
    Using sidekiq-unique-jobs 3.0.13

**Comment by mhenrixon** [comment]
See the section about sidekiq testing. https://github.com/mperham/sidekiq/wiki/Testing
Long story short just set `Sidekiq::Testing.fake!` does that help at all?

**Comment by mhenrixon** [comment]
It should only ever set it to whatever you set it to in the near future.
