### ISSUE TITLE
Optimize Redis usage

### ISSUE THREAD

**Issue by mperham** [mhenrixon/sidekiq-unique-jobs#89]
Right now [the uniqueness check](https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib/sidekiq_unique_jobs/middleware/client/strategies/unique.rb#L48) requires three network round trips to Redis for each job pushed:

1. watch
2. get
3. (multi / setex) || unwatch

Redis 2.6.12+ has new flags for `set` which potentially allow this operation with a single command:

```
conn.set(payload_hash, 1 || 2, nx: true, ex: expires_at)
```

You don't document a minimum Redis version but requiring Redis 2.6+ is your choice.

**Comment by mperham** [comment]
To be honest, I'm not positive all the semantics are met by this change but the performance win is so big, I think it's something to consider.

**Comment by mhenrixon** [comment]
Didn't really have to change anything except make it simpler. Thanks for the intel @mperham !
