### ISSUE TITLE
Latest release is breaking

### ISSUE THREAD

**Issue by kapso** [mhenrixon/sidekiq-unique-jobs#90]
Rolling back to `'3.0.13` fixed the issue. Jobs dont get created I think.

**Comment by mhenrixon** [comment]
Check README and changelog. Sounds like you are on an old redis version.

**Comment by kapso** [comment]
We are on version `2.8.12`

**Comment by mhenrixon** [comment]
Then provide a failing test and I'll reopen this issue.

**Comment by kapso** [comment]
Confirmed `SidekiqUniqueJobs.config.unique_storage_method = :old` fixed the issue

I will provide a failing test. Thanks for your work.

**Comment by smeyfroi** [comment]
Another data point: I have the same problem and solution as @kapso, but with ```redis_version:2.8.17```.

**Comment by mhenrixon** [comment]
This will be closed shortly.

**Comment by smeyfroi** [comment]
@mhenrixon you know the underlying issue? Would be awesome if so!

**Comment by Fredar** [comment]
Initially I had a problem with ActiveJob, so I decided to switch to `workers`, but the problem persisted when I tried to run `perform_in`.

Dropping version to `3.0.13` worked like a charm.
No other gem was changed.

**Comment by mhenrixon** [comment]
This should be fixed on master report if not and I will revisit the issue.
