### ISSUE TITLE
Jobs can unlock mutexes they don't own 

### ISSUE THREAD

**Issue by pik** [mhenrixon/sidekiq-unique-jobs#94]
This happens with perform_at or when a job runs longer than the key_expire time, this is also explicitly advised against in the [redis docs](http://redis.io/topics/distlock).

**Comment by mhenrixon** [comment]
Am I understanding it correctly that the new job gets unlocked by a newer job is there something I am missing?

**Comment by pik** [comment]
So at the moment jobs do not check if they were the ones which originally set a mutex when unlocking -- meaning there are conditions where the job will delete a mutex that another job has set (if it's own has already expired).

**Comment by mhenrixon** [comment]
Closed by #96
