### ISSUE TITLE
Testing functions should be moved out of production code 

### ISSUE THREAD

**Issue by pik** [mhenrixon/sidekiq-unique-jobs#95]
I don't know why this was originally authored in this way -- but this seems like particularly bad style, there is no reason these functions are required to be in the production code, rather than added specifically in the test setup. 

https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib%2Fsidekiq_unique_jobs%2Fmiddleware%2Fclient%2Funique_jobs.rb#L9

https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib%2Fsidekiq_unique_jobs%2Fmiddleware%2Fclient%2Fstrategies%2Funique.rb#L5

https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib%2Fsidekiq_unique_jobs%2Fconnectors.rb#L1

**Comment by mhenrixon** [comment]
Totally agree on that!

**Comment by mhenrixon** [comment]
If you have any better suggestions I am all ears.

**Comment by pik** [comment]
@mhenrixon Thanks for the response - I was hoping to make a PR for this (to patch the relevant classes from the spec_helper.rb or another one of the files which only runs on test) -- but I haven't had a chance to do this yet.

**Comment by mhenrixon** [comment]
@pik check current master if that make sense to you.
